import ts from 'typescript';
import type {SourceFile} from './types';
export function dependencyContext(prompt:string,files:SourceFile[]){
 const paths=new Set(files.map(f=>f.path)),edges=new Map<string,Set<string>>();let uncertain=false;
 const resolve=(from:string,spec:string)=>{if(!spec.startsWith('.')&&!spec.startsWith('@/'))return null;const segments=spec.startsWith('@/')?[]:from.split('/').slice(0,-1);for(const part of (spec.startsWith('@/')?spec.slice(2):spec).split('/')){if(part==='..')segments.pop();else if(part&&part!=='.')segments.push(part)}const p=segments.join('/');return [p,...['.ts','.tsx','.js','.jsx','.css','/index.ts','/index.tsx'].map(e=>p+e)].find(x=>paths.has(x))??null;};
 for(const f of files){const deps=new Set<string>();edges.set(f.path,deps);if(!/\.[jt]sx?$/.test(f.path))continue;const ast=ts.createSourceFile(f.path,f.content,ts.ScriptTarget.Latest,true);if((ast as any).parseDiagnostics?.length)uncertain=true;const visit=(n:ts.Node)=>{if(ts.isImportDeclaration(n)||ts.isExportDeclaration(n)){if(n.moduleSpecifier&&ts.isStringLiteral(n.moduleSpecifier)){const v=n.moduleSpecifier.text,t=resolve(f.path,v);if(t)deps.add(t);else if(v.startsWith('.')||v.startsWith('@/'))uncertain=true;}}if(ts.isCallExpression(n)&&(n.expression.kind===ts.SyntaxKind.ImportKeyword||n.expression.getText(ast)==='require')){const arg=n.arguments[0];if(!arg||!ts.isStringLiteral(arg))uncertain=true;else{const t=resolve(f.path,arg.text);if(t)deps.add(t);else if(arg.text.startsWith('.')||arg.text.startsWith('@/'))uncertain=true;}}if(ts.isCallExpression(n)&&n.expression.getText(ast)==='fetch'){const a=n.arguments[0];if(a&&ts.isStringLiteral(a)&&a.text.startsWith('/')){const path='app'+a.text.split('?')[0]+'/route.ts';if(paths.has(path))deps.add(path);else uncertain=true;}else uncertain=true;}if(ts.isJsxAttribute(n)&&n.name.getText(ast)==='href'&&n.initializer&&ts.isStringLiteral(n.initializer)&&n.initializer.text.startsWith('/')){const base='app'+n.initializer.text.replace(/\/$/,'');const path=[base+'/page.tsx',base+'/page.ts'].find(x=>paths.has(x));if(path)deps.add(path);else uncertain=true;}ts.forEachChild(n,visit);};visit(ast);}
 const words=new Set(prompt.toLowerCase().match(/[a-z][a-z0-9_-]*/g)??[]);const mentioned=files.filter(f=>{const name=f.path.split('/').at(-1)!.replace(/\.[^.]+$/,'').toLowerCase();return prompt.includes(f.path)||(name.length>=4&&!['page','layout','route','index','globals','package','studio.tests','next-env.d'].includes(name)&&words.has(name))}).map(f=>f.path);const selected=new Set(mentioned);
 if(!mentioned.length||uncertain||/\b(entire|across|all pages|redesign|architecture)\b/i.test(prompt))files.forEach(f=>selected.add(f.path));
 else {let changed=true;while(changed){changed=false;for(const [f,deps]of edges)if(selected.has(f)||[...deps].some(d=>selected.has(d))){for(const p of [f,...deps])if(!selected.has(p)){selected.add(p);changed=true}}}for(const f of files)if(/(?:layout\.tsx|\.css|package\.json|tsconfig\.json|studio\.tests\.json)$/.test(f.path))selected.add(f.path);}
 return {files:files.filter(f=>selected.has(f.path)),index:files.map(f=>({path:f.path,imports:[...(edges.get(f.path)??[])]})),omitted:files.filter(f=>!selected.has(f.path)).reduce((n,f)=>n+f.content.length,0),uncertain};
}
