// Serialized into opaque HTML previews and temporary Next.js Sandbox previews.
// Reports are advisory observations from untrusted app code, not security attestations.
export function designBridge(channel:string,parentOrigin='*'){return `(()=>{const channel=${JSON.stringify(channel)},origin=${JSON.stringify(parentOrigin)};let selecting=false;const send=data=>parent.postMessage({channel,kind:'studio-design',...data},origin);
addEventListener('message',e=>{if(e.source!==parent||(origin!=='*'&&e.origin!==origin)||e.data?.channel!==channel)return;if(e.data.action==='select-mode'){selecting=!!e.data.enabled;document.documentElement.style.cursor=selecting?'crosshair':'';}if(e.data.action==='audit'){const findings=[];const add=(category,element,message,fix)=>{if(findings.length<40)findings.push({category,element,message,fix});};const label=el=>el.dataset.studioElement||el.id||el.tagName.toLowerCase()+': '+(el.textContent||el.alt||'').trim().slice(0,50);const visible=el=>{const b=el.getBoundingClientRect(),s=getComputedStyle(el);return b.width>0&&b.height>0&&s.visibility!=='hidden'&&s.display!=='none';};
if(document.documentElement.scrollWidth>innerWidth+2)add('responsive','page','Content overflows the viewport.','Remove fixed widths and test narrow screens.');
if(!document.querySelector('h1'))add('hierarchy','page','No primary heading was found.','Add one descriptive h1 for the page.');
const lum=rgb=>{const v=rgb.slice(0,3).map(x=>{x=x/255;return x<=.04045?x/12.92:Math.pow((x+.055)/1.055,2.4)});return v[0]*.2126+v[1]*.7152+v[2]*.0722;};
for(const el of [...document.body.querySelectorAll('*')].slice(0,2000)){if(!visible(el)||el.closest('script,style,svg'))continue;const s=getComputedStyle(el),b=el.getBoundingClientRect();if(el.tagName==='IMG'&&!el.hasAttribute('alt'))add('accessibility',label(el),'Image lacks alternative text.','Describe the image or use empty alt for decoration.');if(el.tagName==='IMG'&&el.complete&&!el.naturalWidth)add('assets',label(el),'Image did not load.','Check its image URL.');
if(el.matches('button,a[href],input:not([type=hidden]),select,textarea')){if(!(el.textContent?.trim()||el.getAttribute('aria-label')||el.labels?.length||el.getAttribute('aria-labelledby')||(el.type==='submit'&&el.value)))add('accessibility',label(el),'Control has no accessible name.','Add visible label text or an aria-label.');if(b.width<24||b.height<24)add('touch',label(el),'Control is smaller than 24 pixels.','Increase its hit area and spacing.');}
if(!el.children.length&&el.textContent?.trim()){if(parseFloat(s.fontSize)<12)add('typography',label(el),'Text is smaller than 12 pixels.','Increase small text for readability.');const fg=s.color.match(/[\\d.]+/g)?.map(Number);let ancestor=el,bg;while(ancestor){const a=getComputedStyle(ancestor).backgroundColor.match(/[\\d.]+/g)?.map(Number);if(a&&(a.length<4||a[3]===1)){bg=a;break;}ancestor=ancestor.parentElement;}if(fg&&bg&&(fg.length<4||fg[3]===1)&&s.backgroundImage==='none'){const x=lum(fg),y=lum(bg),ratio=(Math.max(x,y)+.05)/(Math.min(x,y)+.05),large=parseFloat(s.fontSize)>=24||(parseFloat(s.fontSize)>=18.66&&parseInt(s.fontWeight)>=700);if(ratio<(large?3:4.5))add('contrast',label(el),'Possible low contrast: '+ratio.toFixed(2)+':1.','Use stronger contrast; manually review gradients and image backgrounds.');}}
}send({report:{viewport:{width:innerWidth,height:innerHeight},url:location.pathname,findings,checkedAt:new Date().toISOString()}});}});
addEventListener('click',e=>{if(!selecting)return;const el=e.target.closest?.('[data-studio-element]');if(!el)return;e.preventDefault();e.stopImmediatePropagation();send({selected:el.dataset.studioElement});},true);})();`;}
export type DesignFinding={category:string;element:string;message:string;fix:string};
export type DesignAudit={viewport:{width:number;height:number};url:string;findings:DesignFinding[];checkedAt:string};
