import {z} from 'zod';
import {artifactSchema,validateArtifact} from './artifacts';
import {isFullstack,acceptanceTests} from './fullstack-project';
import type {SourceFile} from './types';
export const featureSchema=z.object({id:z.uuid(),name:z.string().trim().min(1).max(80),description:z.string().max(2000),files:artifactSchema.shape.files,sql:z.string().max(50000),created_at:z.string()});
export type Feature=z.infer<typeof featureSchema>;
export const featureKits=[{id:'faq',name:'FAQ accordion',description:'Accessible questions with native expand/collapse controls.'},{id:'calculator',name:'Price calculator',description:'A live estimate based on seats and monthly or annual billing.'},{id:'tasks',name:'Personal checklist',description:'Add, complete and remove tasks. Data stays in the app browser.'}] as const;
export type KitId=typeof featureKits[number]['id'];
const css='.studio-kit{max-width:800px;margin:32px auto;padding:28px;border:1px solid #cbd5e1;border-radius:16px;background:#fff;color:#0f172a;font:16px/1.6 system-ui}.studio-kit label{display:block;margin:16px 0}.studio-kit input,.studio-kit select,.studio-kit button{font:inherit;padding:10px;margin:4px;max-width:100%;box-sizing:border-box}.studio-kit button{cursor:pointer}.studio-kit details{padding:12px;border-bottom:1px solid #cbd5e1}.studio-kit summary{cursor:pointer}.studio-kit li{display:flex;align-items:center;flex-wrap:wrap;gap:12px}.studio-kit output{display:block;font-size:24px;font-weight:700}';
const faq='<section class="studio-kit" id="studio-faq"><h2>Frequently asked questions</h2><details><summary>How do I get started?</summary><p>Choose the service that fits your needs and contact our team.</p></details><details><summary>Can I change my plan?</summary><p>Contact our team to discuss the available options.</p></details></section>';
const calculator='<section class="studio-kit" id="studio-calculator"><h2>Estimate your plan</h2><p>Illustrative pricing: $20 per seat per month; annual billing saves 20%.</p><label>Seats<input name="seats" type="number" min="1" max="1000" value="5" /></label><label>Billing<select name="billing"><option value="monthly">Monthly</option><option value="annual">Annual</option></select></label><output aria-live="polite">$100.00 per month</output></section>';
const tasks='<section class="studio-kit" id="studio-tasks"><h2>Personal checklist</h2><p>Saved on this browser only.</p><form><label>New task<input name="task" required maxlength="120" /></label><button type="submit">Add task</button></form><p role="status" aria-live="polite"></p><ul></ul></section>';
const calcJs="const root=document.getElementById('studio-calculator');function update(){const seats=Math.max(1,Math.min(1000,Number(root.querySelector('[name=seats]').value)||1));const annual=root.querySelector('[name=billing]').value==='annual';root.querySelector('output').textContent=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(seats*20*(annual?.8:1))+' per month'+(annual?' · billed annually':'');}root.addEventListener('input',update);root.addEventListener('change',update);update();";
const taskJs="const root=document.getElementById('studio-tasks'),key='studio-personal-checklist-v1';let items=[];try{const saved=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(saved))items=saved.filter(x=>typeof x.text==='string'&&typeof x.done==='boolean').slice(0,100);}catch{}function render(){root.querySelector('ul').replaceChildren(...items.map((item,i)=>{const li=document.createElement('li'),check=document.createElement('input'),label=document.createElement('label'),remove=document.createElement('button');check.type='checkbox';check.checked=item.done;label.append(check,document.createTextNode(item.text));check.addEventListener('change',()=>{items[i].done=check.checked;save()});remove.type='button';remove.textContent='Remove';remove.setAttribute('aria-label','Remove '+item.text);remove.addEventListener('click',()=>{items.splice(i,1);save()});li.append(label,remove);return li}));}function save(){try{localStorage.setItem(key,JSON.stringify(items));root.querySelector('[role=status]').textContent='Saved on this browser.';}catch{root.querySelector('[role=status]').textContent='Storage unavailable. Changes last only until this page closes.';}render()}root.querySelector('form').addEventListener('submit',e=>{e.preventDefault();const input=root.querySelector('[name=task]');if(!input.value.trim())return;if(items.length>=100){root.querySelector('[role=status]').textContent='Limit of 100 tasks.';return}items.push({text:input.value.trim(),done:false});input.value='';save()});render();";
const reactCalc=`'use client';import {useState} from 'react';export default function Kit(){const [seats,setSeats]=useState(5),[annual,setAnnual]=useState(false);return <section className="studio-kit"><h1>Estimate your plan</h1><p>Illustrative pricing: $20 per seat per month; annual billing saves 20%.</p><label>Seats<input type="number" min="1" max="1000" value={seats} onChange={e=>setSeats(Math.max(1,Math.min(1000,Number(e.target.value)||1)))}/></label><label>Billing<select value={annual?'annual':'monthly'} onChange={e=>setAnnual(e.target.value==='annual')}><option value="monthly">Monthly</option><option value="annual">Annual</option></select></label><output aria-live="polite">{new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(seats*20*(annual?.8:1))} per month{annual?' · billed annually':''}</output></section>}`;
const reactTasks=`'use client';import {useState,useEffect} from 'react';type Task={text:string;done:boolean};export default function Kit(){const [items,setItems]=useState<Task[]>([]),[text,setText]=useState(''),[ready,setReady]=useState(false),[status,setStatus]=useState('');useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('studio-personal-checklist-v1')||'[]');if(Array.isArray(saved))setItems(saved.filter(x=>typeof x.text==='string'&&typeof x.done==='boolean').slice(0,100));}catch{}setReady(true)},[]);useEffect(()=>{if(!ready)return;try{localStorage.setItem('studio-personal-checklist-v1',JSON.stringify(items));setStatus('Saved on this browser.')}catch{setStatus('Storage unavailable. Changes last only until this page closes.')}},[items,ready]);return <section className="studio-kit"><h1>Personal checklist</h1><p>Saved on this browser only.</p><form onSubmit={e=>{e.preventDefault();if(!text.trim()||items.length>=100)return;setItems([...items,{text:text.trim(),done:false}]);setText('')}}><label>New task<input required maxLength={120} value={text} onChange={e=>setText(e.target.value)}/></label><button disabled={!ready||items.length>=100}>Add task</button></form><p role="status" aria-live="polite">{status}</p><ul>{items.map((item,i)=><li key={i}><label><input type="checkbox" checked={item.done} onChange={e=>setItems(items.map((x,j)=>i===j?{...x,done:e.target.checked}:x))}/>{item.text}</label><button type="button" aria-label={'Remove '+item.text} onClick={()=>setItems(items.filter((_,j)=>i!==j))}>Remove</button></li>)}</ul></section>}`;
export function installKit(files:SourceFile[],id:KitId){if(!featureKits.some(k=>k.id===id))throw new Error('Unknown feature kit.');const next=isFullstack(files);const path=next?`app/studio-${id}/page.tsx`:`components/studio-${id}.js`;if(files.some(f=>f.path===path)||files.some(f=>f.path==='index.html'&&f.content.includes('id="studio-'+id+'"')))throw new Error('This feature is already installed. Edit its existing source.');
 if(next){const existingTests=files.some(f=>f.path==='studio.tests.json')?acceptanceTests(files):{requirements:[]};const requirement={id:'studio-kit-'+id,description:'Reusable '+id+' interaction works',steps:[{action:'goto',value:'/studio-'+id},...(id==='faq'?[{action:'click',target:'details:first-of-type summary'},{action:'visible',target:'details:first-of-type[open] p'}]:id==='calculator'?[{action:'fill',target:'input[type=number]',value:'3'},{action:'text',target:'output',value:'$60.00'}]:[{action:'fill',target:'form input',value:'Test checklist item'},{action:'click',target:'form button'},{action:'text',target:'ul li',value:'Test checklist item'}])]};const tests={path:'studio.tests.json',content:JSON.stringify({requirements:[...existingTests.requirements,requirement]},null,2)};if(existingTests.requirements.length>=12)throw new Error('This project already has 12 acceptance requirements. Consolidate tests before installing another pack.');const page=id==='faq'?'export default function Kit(){return '+faq.replace('class=','className=').replace('<h2>','<h1>').replace('</h2>','</h1>')+'}':id==='calculator'?reactCalc:reactTasks;const stylePath='app/studio-'+id+'/kit.css';return [...files.filter(f=>f.path!=='studio.tests.json'),tests,{path,content:"import './kit.css';\n"+page},{path:stylePath,content:css}].map(f=>f.path===path&&f.content.includes("'use client';")?{...f,content:"'use client';\n"+f.content.replace("'use client';",'')}:f);}
 const html=files.find(f=>f.path==='index.html');if(!html||!/<\/body\s*>/i.test(html.content))throw new Error('A complete HTML body is required.');const section=id==='faq'?faq:id==='calculator'?calculator:tasks;const content=html.content.replace(/<\/body\s*>/i,()=>'<style>'+css+'</style>'+section+(id==='faq'?'':`<script type="module" src="./${path}"></script>`)+'</body>');return [...files.map(f=>f.path==='index.html'?{...f,content}:f),...(id==='faq'?[]:[{path,content:id==='calculator'?calcJs:taskJs}])];
}
export function validateFeature(input:unknown){const feature=featureSchema.parse(input);validateArtifact({name:feature.name,summary:feature.description||'Reusable blueprint',files:feature.files,sql:feature.sql});return feature;}
// Browser-only blueprints are durable IndexedDB records; cloud uses the authenticated API.
export async function localFeatures(action:'list'|'save'|'delete',value?:Feature|string):Promise<Feature[]>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('5511-feature-library',1);r.onupgradeneeded=()=>r.result.createObjectStore('features',{keyPath:'id'});r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)});try{return await new Promise((resolve,reject)=>{const tx=db.transaction('features',action==='list'?'readonly':'readwrite'),store=tx.objectStore('features');if(action==='save')store.put(validateFeature(value));if(action==='delete')store.delete(value as string);const r=store.getAll();tx.oncomplete=()=>resolve(r.result);tx.onerror=()=>reject(new Error('Feature library could not be saved.'));})}finally{db.close()}}
