import {z} from 'zod';
import type {SourceFile} from './types';
export const approvedPackages:Record<string,string>={next:'16.2.1',react:'19.2.4','react-dom':'19.2.4','@supabase/supabase-js':'2.99.1',zod:'4.3.6','lucide-react':'0.577.0'};
export const fullstackPath=/^(?:package\.json|tsconfig\.json|next-env\.d\.ts|studio\.tests\.json|(?:app|components|lib)\/(?:[a-zA-Z0-9_()[\]-]+\/)*[a-zA-Z0-9_()[\]-]+\.(?:tsx?|jsx?|css|json))$/;
export const isFullstack=(files:SourceFile[])=>files.some(f=>f.path==='package.json');
export const runtimeInstructions=`Build a Next.js App Router application using React and TypeScript. Use app/page.tsx, app/layout.tsx, app/globals.css, app/**/page.tsx for routes and app/api/**/route.ts for server functions. Use 'use client' only where needed. Preserve package.json, tsconfig.json and next-env.d.ts. Approved pinned packages: ${JSON.stringify(approvedPackages)}. No shell scripts, install hooks, arbitrary dependencies, environment files, secret keys, remote scripts or external fonts. The sandbox has no Studio credentials. No JSX in .ts files. Keep files small and reuse components. Return only changed files or exact patches. Requirements must have executable acceptance tests in studio.tests.json: {"requirements":[{"id":"booking","description":"user-visible behavior","steps":[{"action":"goto","value":"/"},{"action":"fill","target":"input[name=email]","value":"test@example.test"},{"action":"click","target":"button[type=submit]"},{"action":"visible","target":"[role=status]","value":""}]}]}. Actions: goto, fill, click, visible, text, url. Every requirement needs an assertion (visible/text/url); use real selectors and exact expected results, never edit tests merely to hide a failure. Test local APIs with isolated data; do not claim real database persistence until separately configured and verified. Preserve existing acceptance requirements on refinements. No external navigation in tests. Return SQL separately for review, never execute migrations. Use environment variables NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY for the app's own database; show clear missing-connection states. Describe unimplemented requirements honestly.`;
export function fullstackTemplate():SourceFile[]{return [
 {path:'package.json',content:JSON.stringify({name:'studio-app',private:true,scripts:{dev:'next dev --hostname 0.0.0.0',build:'next build',start:'next start --hostname 0.0.0.0'},dependencies:{next:approvedPackages.next,react:approvedPackages.react,'react-dom':approvedPackages['react-dom']},devDependencies:{typescript:'5.9.3','@types/node':'22.19.15','@types/react':'19.2.14','@types/react-dom':'19.2.3'}},null,2)},
 {path:'tsconfig.json',content:JSON.stringify({compilerOptions:{target:'ES2020',lib:['dom','dom.iterable','esnext'],strict:true,noEmit:true,esModuleInterop:true,module:'esnext',moduleResolution:'bundler',resolveJsonModule:true,isolatedModules:true,jsx:'react-jsx',plugins:[{name:'next'}],paths:{'@/*':['./*']}},include:['next-env.d.ts','**/*.ts','**/*.tsx','.next/types/**/*.ts'],exclude:['node_modules']})},
 {path:'next-env.d.ts',content:'/// <reference types="next" />\n/// <reference types="next/image-types/global" />'},
 {path:'app/layout.tsx',content:"import './globals.css'; export default function Layout({children}:{children:React.ReactNode}){return <html lang=\"en\"><body>{children}</body></html>}"},
 {path:'app/page.tsx',content:'export default function Page(){return <main><h1>Your app foundation</h1><p>Build in progress.</p></main>}'},
 {path:'app/globals.css',content:'body{margin:0;font-family:Arial,sans-serif;color:#0f172a;background:#fff}main{max-width:1100px;margin:auto;padding:48px}button{cursor:pointer}'}];}
export function validateFullstack(files:SourceFile[]){
 for(const f of files)if(!fullstackPath.test(f.path))throw new Error('Unsupported full-stack path: '+f.path);
 for(const path of ['package.json','app/layout.tsx','app/page.tsx'])if(!files.some(f=>f.path===path))throw new Error('Missing runtime file: '+path);
 const manifest=JSON.parse(files.find(f=>f.path==='package.json')!.content),base=JSON.parse(fullstackTemplate()[0].content);
 const same=(a:Record<string,unknown>,b:Record<string,unknown>)=>!!a&&Object.keys(a).length===Object.keys(b).length&&Object.entries(b).every(([k,v])=>a[k]===v);
 if(!same(manifest.scripts,base.scripts))throw new Error('Runtime scripts must match the controlled template.');
 for(const key of Object.keys(manifest))if(!['name','private','scripts','dependencies','devDependencies'].includes(key))throw new Error('Unsupported package manifest field: '+key);
 for(const [name,version] of Object.entries(manifest.dependencies??{}))if(approvedPackages[name]!==version)throw new Error('Unsupported package/version: '+name);
 for(const name of ['next','react','react-dom'])if(manifest.dependencies?.[name]!==approvedPackages[name])throw new Error('Required runtime dependency: '+name);
 if(!same(manifest.devDependencies,base.devDependencies))throw new Error('Keep the controlled TypeScript dependencies.');
}
export const acceptanceSchema=z.object({requirements:z.array(z.object({id:z.string().min(1).max(80),description:z.string().min(5).max(500),steps:z.array(z.object({action:z.enum(['goto','fill','click','visible','text','url']),target:z.string().max(300).default(''),value:z.string().max(1000).default('')})).min(2).max(15).refine(s=>s.some(x=>['visible','text','url'].includes(x.action)),'Requirement needs an assertion')})).min(1).max(12)});
export function acceptanceTests(files:SourceFile[]){const file=files.find(f=>f.path==='studio.tests.json');if(!file)throw new Error('No executable acceptance requirements were generated.');const tests=acceptanceSchema.parse(JSON.parse(file.content));for(const r of tests.requirements)for(const s of r.steps){if(['text','url','goto'].includes(s.action)&&!s.value.trim())throw new Error('Test expectations cannot be empty.');if(['fill','click','visible','text'].includes(s.action)&&!s.target.trim())throw new Error('Test selector is required.');if(['goto','url'].includes(s.action)&&(!s.value.startsWith('/')||s.value.startsWith('//')||/[\\\r\n]/.test(s.value)))throw new Error('Tests must stay on the isolated application.');}if(new Set(tests.requirements.map(r=>r.id)).size!==tests.requirements.length)throw new Error('Duplicate requirement IDs');return tests;}
