import {createCipheriv,createDecipheriv,randomBytes} from 'node:crypto';
import {sharedUsageDb} from './shared-usage';
import {HttpError} from './server';
export function jobsDb(){const db=sharedUsageDb();if(!db)throw new HttpError(503,'Background builds need the Studio Supabase server connection.');return db;}
function key(){const value=process.env.STUDIO_JOB_ENCRYPTION_KEY;if(!value||!/^[a-f0-9]{64}$/i.test(value))throw new HttpError(503,'Set STUDIO_JOB_ENCRYPTION_KEY to a stable 32-byte hex secret on the Studio server.');return Buffer.from(value,'hex');}
export function sealJobCredential(value:string){const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',key(),iv);const bytes=Buffer.concat([c.update(value,'utf8'),c.final()]);return Buffer.concat([iv,c.getAuthTag(),bytes]).toString('base64');}
export function openJobCredential(value:string){const bytes=Buffer.from(value,'base64'),c=createDecipheriv('aes-256-gcm',key(),bytes.subarray(0,12));c.setAuthTag(bytes.subarray(12,28));return Buffer.concat([c.update(bytes.subarray(28)),c.final()]).toString('utf8');}
export async function loadJob(id:string){const db=jobsDb();const {data:job,error}=await db.from('studio_build_jobs').select('*').eq('id',id).single();if(error||!job)throw new Error('Build job unavailable.');return job;}
export async function assertJobAccess(job:any){const db=jobsDb();const [{data:{user},error},{data:p}]=await Promise.all([db.auth.admin.getUserById(job.user_id),db.from('projects').select('*').eq('id',job.project_id).single()]);if(error||!user||!p)throw new Error('Project access no longer available.');const allowed=process.env.STUDIO_ALLOWED_EMAILS?.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);if(allowed?.length&&!allowed.includes(user.email?.toLowerCase()??''))throw new Error('Workspace access removed.');if(p.owner_id!==user.id){const {data:a}=await db.from('project_access').select('role').eq('project_id',p.id).eq('email',user.email?.toLowerCase()??'').maybeSingle();if(!user.email_confirmed_at||a?.role!=='editor')throw new Error('Editing access removed.');}return p;}
export async function finishJob(id:string,status:'completed'|'failed'|'cancelled',error?:string,report?:unknown){const db=jobsDb();const {error:e}=await db.from('studio_build_jobs').update({status,error:error?.slice(0,5000)??null,report,updated_at:new Date().toISOString()}).eq('id',id);if(e)throw new Error('Job status could not be saved.');await db.from('studio_job_secrets').delete().eq('job_id',id);}

export async function jobProgress(id:string,progress:string){const {error}=await jobsDb().from('studio_build_jobs').update({progress,updated_at:new Date().toISOString()}).eq('id',id).in('status',['queued','running']);if(error)throw new Error('Build progress could not be saved.');}
