import type {SourceFile} from './types';
import {renderPreview} from './artifacts';
export type PreviewReport={errors:string[];warnings:string[];checks:number};
// Disposable, opaque-origin iframe. No cookies, backend writes, form submission or navigation.
export function verifyPreview(files:SourceFile[]):Promise<PreviewReport>{return new Promise(resolve=>{
 const frame=document.createElement('iframe'),channel=crypto.randomUUID();frame.setAttribute('sandbox','allow-scripts');frame.setAttribute('aria-hidden','true');frame.style.cssText='position:fixed;left:-10000px;top:0;width:1280px;height:900px;visibility:hidden;';
 let done=false;const finish=(report:PreviewReport)=>{if(done)return;done=true;clearTimeout(timer);window.removeEventListener('message',receive);frame.remove();resolve(report)};
 const receive=(event:MessageEvent)=>{if(event.source!==frame.contentWindow||event.data?.channel!==channel||event.data?.kind!=='studio-checks')return;const d=event.data.report;if(!d||!Array.isArray(d.errors)||!Array.isArray(d.warnings))return;finish({errors:d.errors.filter((x:unknown)=>typeof x==='string').slice(0,20).map((x:string)=>x.slice(0,300)),warnings:d.warnings.filter((x:unknown)=>typeof x==='string').slice(0,20).map((x:string)=>x.slice(0,300)),checks:Number(d.checks)||0});};
 const timer=setTimeout(()=>finish({errors:['Browser verification timed out. Review the preview before continuing.'],warnings:[],checks:0}),12000);window.addEventListener('message',receive);
 const bootstrap=`(()=>{const errors=[],warnings=[];let checks=0;addEventListener('error',e=>{if(e.message)errors.push(e.message);else if(e.target?.tagName==='SCRIPT')errors.push('A required script could not load')},true);addEventListener('unhandledrejection',e=>errors.push(String(e.reason?.message||e.reason)));addEventListener('securitypolicyviolation',e=>(e.violatedDirective.startsWith('script-src')?errors:warnings).push('Sandbox blocked '+e.violatedDirective));addEventListener('submit',e=>e.preventDefault(),true);addEventListener('click',e=>{if(e.target.closest?.('a'))e.preventDefault()},true);addEventListener('load',()=>setTimeout(async()=>{try{const ids=new Set();document.querySelectorAll('[id]').forEach(el=>{checks++;if(ids.has(el.id))warnings.push('Duplicate id: '+el.id);ids.add(el.id)});document.querySelectorAll('a[href^="#"]').forEach(a=>{checks++;try{const id=decodeURIComponent(a.getAttribute('href').slice(1));if(id&&!document.getElementById(id))errors.push('Missing navigation target #'+id)}catch{errors.push('Invalid navigation target')}});document.querySelectorAll('button,input:not([type=hidden]),select,textarea').forEach(el=>{checks++;if(!(el.getAttribute('aria-label')||el.getAttribute('aria-labelledby')||el.labels?.length||el.textContent?.trim()||el.getAttribute('title')||(el.type==='submit'&&el.value)))warnings.push('Control needs an accessible name: '+el.tagName)});for(const button of [...document.querySelectorAll('button[type=button][data-studio-test]')].slice(0,8)){if(button.closest('form')||button.disabled)continue;checks++;button.click();await new Promise(r=>setTimeout(r,80));const selector=button.getAttribute('data-studio-expect');if(selector){const el=document.querySelector(selector);if(!el||getComputedStyle(el).display==='none'||getComputedStyle(el).visibility==='hidden'||el.hidden)errors.push('Interaction expectation failed: '+selector)}else warnings.push('Test button has no expected result selector');}}catch(e){errors.push(String(e.message))}parent.postMessage({channel:${JSON.stringify(channel)},kind:'studio-checks',report:{errors:[...new Set(errors)],warnings:[...new Set(warnings)],checks}},'*')},700));})();`;
 // Strip model-supplied CSP/base tags so the test policy is applied before any script.
 const page=renderPreview(files).replace(/<meta\b[^>]*http-equiv[^>]*>/gi,'').replace(/<base\b[^>]*>/gi,'');
 const policy=`<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'unsafe-inline' data: blob: https://esm.sh; style-src 'unsafe-inline'; img-src data: blob:; connect-src 'none'; form-action 'none'; frame-src 'none'; base-uri 'none'">`;
 frame.srcdoc=policy+'<script>'+bootstrap+'</script>'+page;document.body.appendChild(frame);
});}
