import {z} from 'zod';
import ts from 'typescript';
import {isFullstack} from './fullstack-project';
import type {SourceFile} from './types';
const safeLink=z.string().max(500).refine(s=>/^(?:\/(?!\/)|#[a-zA-Z0-9_-]|https:\/\/)/.test(s)&&!/[\\\s"<>]/.test(s),'Use a relative path, anchor, or HTTPS link.');
export const sectionKinds=['hero','features','stats','process','testimonials','pricing','faq','cta'] as const;
export const sectionSchema=z.object({version:z.literal(1),id:z.uuid(),name:z.string().trim().min(1).max(80),kind:z.enum(sectionKinds),eyebrow:z.string().max(100),title:z.string().min(1).max(160),body:z.string().max(700),button:z.string().max(60),href:safeLink,accent:z.string().regex(/^#[a-fA-F0-9]{6}$/),dark:z.boolean(),rounded:z.boolean(),items:z.array(z.object({title:z.string().max(100),body:z.string().max(500)})).min(1).max(6)});
export type Section=z.infer<typeof sectionSchema>;
export const sectionStarters:Record<Section['kind'],{name:string;title:string;body:string;items:Section['items']}>={
 hero:{name:'Spotlight hero',title:'Big ideas deserve a bold beginning.',body:'Introduce what makes your business different with a clear message and a next step.',items:[{title:'Made for you',body:'Thoughtful details. Lasting impressions.'}]},
 features:{name:'Bento features',title:'Everything you need. Beautifully connected.',body:'Show the benefits that make your product worth choosing.',items:[{title:'Work beautifully',body:'A thoughtful experience from your first click.'},{title:'Move faster',body:'Spend less time setting up and more time creating.'},{title:'Make it yours',body:'Flexible details that fit the way you work.'}]},
 stats:{name:'Impact numbers',title:'Let the results speak.',body:'Replace these sample figures with your verified results before publishing.',items:[{title:'120+',body:'Projects delivered · sample'},{title:'98%',body:'Satisfaction · sample'},{title:'12',body:'Years of experience · sample'}]},
 process:{name:'Step-by-step',title:'From first hello to something great.',body:'Make your process simple to understand.',items:[{title:'Discover',body:'Tell us what you have in mind.'},{title:'Create',body:'We turn your goals into a thoughtful solution.'},{title:'Launch',body:'Review the details and share it with the world.'}]},
 testimonials:{name:'Customer stories',title:'Good work gets people talking.',body:'Sample testimonials. Replace with real quotes and permission before publishing.',items:[{title:'Customer name',body:'“A wonderful experience from start to finish.”'},{title:'Customer name',body:'“Thoughtful, clear and easy to work with.”'}]},
 pricing:{name:'Pricing cards',title:'A plan for your next chapter.',body:'Sample pricing. Customize inclusions and link to your actual sign-up flow.',items:[{title:'Starter · $29',body:'The essentials for getting started.'},{title:'Growth · $79',body:'More room for your growing ambitions.'},{title:'Custom',body:'A tailored plan for your organization.'}]},
 faq:{name:'Editorial FAQ',title:'A few things you might be wondering.',body:'Clear answers make the next step easier.',items:[{title:'How do I get started?',body:'Contact our team to discuss your goals.'},{title:'Can you customize the experience?',body:'Yes. Tell us what you need and we can discuss the options.'}]},
 cta:{name:'Bold call to action',title:'Your next great idea starts here.',body:'Give visitors a compelling reason to take the next step.',items:[{title:'Let’s begin',body:'We would love to hear from you.'}]}
};
export function newSection(kind:Section['kind'],id:string):Section{const s=sectionStarters[kind];return {version:1,id,kind,name:s.name,eyebrow:'THE NEXT CHAPTER',title:s.title,body:s.body,button:'Get in touch',href:'/contact',accent:'#6155e8',dark:false,rounded:true,items:s.items.map(i=>({...i}))};}
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function renderSection(input:Section){const s=sectionSchema.parse(input),id='section-'+s.id.replaceAll('-',''),e=escape;
 const cards=s.items.map((i,n)=>s.kind==='faq'?`<details><summary>${e(i.title)}</summary><p>${e(i.body)}</p></details>`:`<article>${s.kind==='process'?`<span class="section-number">0${n+1}</span>`:''}<h3>${e(i.title)}</h3><p>${e(i.body)}</p>${s.kind==='pricing'&&s.button?`<a href="${e(s.href)}">${e(s.button)}</a>`:''}</article>`).join('');
 const html=`<section id="${id}" aria-labelledby="${id}-title" class="section-${s.kind}"><div class="section-inner"><header><p class="section-eyebrow">${e(s.eyebrow)}</p><h2 id="${id}-title">${e(s.title)}</h2><p class="section-intro">${e(s.body)}</p>${s.button&&s.kind!=='pricing'?`<a class="section-button" href="${e(s.href)}">${e(s.button)} <span aria-hidden="true">↗</span></a>`:''}</header>${s.kind==='hero'?'<div class="section-art" aria-hidden="true"><i></i><i></i><i></i><span>MAKE<br>SOMETHING<br>MATTER.</span></div>':s.kind==='cta'?'':`<div class="section-cards">${cards}</div>`}</div></section>`;
 const css=`#${id}{--accent:${s.accent};background:${s.dark?'#111827':'#f7f7fc'};color:${s.dark?'#f8fafc':'#172033'};padding:clamp(32px,6vw,88px) 24px;font:16px/1.65 system-ui;isolation:isolate;overflow:hidden}#${id} *{box-sizing:border-box}#${id} .section-inner{max-width:1100px;margin:auto}#${id} header{max-width:740px}#${id} h2{font-size:clamp(30px,4.5vw,60px);line-height:1.08;letter-spacing:-.05em;margin:18px 0}#${id} p{margin:10px 0;white-space:pre-line}#${id} .section-intro{opacity:.78;max-width:620px}#${id} .section-eyebrow{font-size:11px;letter-spacing:.2em;font-weight:800}#${id} a{display:inline-flex;align-items:center;gap:25px;padding:12px 22px;border-radius:${s.rounded?'100px':'4px'};background:var(--accent);color:white;text-decoration:none;font-weight:650;margin-top:18px}#${id} a:focus-visible,#${id} summary:focus-visible{outline:3px solid currentColor;outline-offset:5px}#${id} .section-cards{display:grid;grid-template-columns:repeat(${Math.min(s.items.length,3)},minmax(0,1fr));gap:18px;margin-top:40px}#${id} article,#${id} details{border:1px solid ${s.dark?'#384255':'#dde0eb'};padding:28px;border-radius:${s.rounded?'22px':'4px'};background:${s.dark?'#1b2436':'white'}}#${id} h3{font-size:${s.kind==='stats'?'42px':'22px'};line-height:1.2;letter-spacing:-.025em;margin:0 0 14px}#${id} article p{opacity:.8}#${id} .section-number{display:block;font-size:36px;font-weight:800;margin-bottom:30px;opacity:.6}#${id}.section-faq .section-cards{grid-template-columns:1fr}#${id} summary{font-weight:700;cursor:pointer}#${id}.section-cta{text-align:center;background:linear-gradient(135deg,${s.dark?'#111827':'#eef0ff'},${s.dark?'#292443':'#e9f8ff'})}#${id}.section-cta header{margin:auto}#${id}.section-cta .section-intro{margin:20px auto}#${id}.section-hero .section-inner{display:grid;grid-template-columns:1.2fr 1fr;gap:40px;align-items:center}#${id} .section-art{position:relative;min-height:330px;border-radius:32px;background:var(--accent);overflow:hidden;display:grid;place-items:center;color:white}#${id} .section-art span{position:relative;font-weight:900;font-size:40px;line-height:1.1;letter-spacing:-.05em;transform:rotate(-8deg)}#${id} .section-art i{position:absolute;width:230px;height:230px;border:35px solid #ffffff25;border-radius:50%;left:-80px;top:-70px}#${id} .section-art i:nth-child(2){left:auto;top:auto;right:-80px;bottom:-70px}#${id} .section-art i:nth-child(3){inset:auto;width:140px;height:140px;border-radius:20px;transform:rotate(25deg)}@media(max-width:650px){#${id} .section-cards,#${id}.section-hero .section-inner{grid-template-columns:1fr}#${id} .section-art{min-height:240px}}`;
 return {id,html,css};
}
export function sectionDocument(s:Section,preview=false){const rendered=renderSection(s),css=rendered.css,html=preview?rendered.html.replace(/ href="[^"]*"/g,' aria-disabled="true"'):rendered.html;return `<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline';"><title>${escape(s.name)}</title><style>body{margin:0}${css}</style></head><body>${html}</body></html>`;}
export const sectionMetadataPath='components/studio-section.json';
export function sectionFeature(s:Section){s=sectionSchema.parse(s);return {id:crypto.randomUUID(),name:s.name,description:'Section Studio · '+s.kind,created_at:new Date().toISOString(),sql:'',files:[{path:'index.html',content:sectionDocument(s)},{path:sectionMetadataPath,content:JSON.stringify(s)}]};}
export function readSection(files:SourceFile[]){const f=files.find(f=>f.path===sectionMetadataPath);return f?sectionSchema.parse(JSON.parse(f.content)):null;}
export function installSection(files:SourceFile[],input:Section,target='app/page.tsx'):SourceFile[]{const s=sectionSchema.parse(input),{id,html,css}=renderSection(s),component='Section'+s.id.replaceAll('-',''),path=`components/${id}.tsx`;
 if(files.some(f=>f.path===path||f.content.includes(`id="${id}"`)))throw new Error('This section is already installed. Edit the existing section or save a copy with a new identity.');
 if(!isFullstack(files)){const page=files.find(f=>f.path==='index.html');if(!page||!/<\/body\s*>/i.test(page.content))throw new Error('This page needs a complete HTML body.');return files.map(f=>f===page?{...f,content:f.content.replace(/<\/body\s*>/i,()=>`<style>${css}</style>${html}</body>`)}:f);}
 const page=files.find(f=>f.path===target);if(!page||!/^app\/(?:[\w()-]+\/)*page\.tsx$/.test(target))throw new Error('Choose an existing page.');
 const parsed=ts.createSourceFile(target,page.content,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX),mains:ts.JsxElement[]=[];
 function visit(node:ts.Node){if(ts.isJsxElement(node)&&node.openingElement.tagName.getText(parsed)==='main')mains.push(node);ts.forEachChild(node,visit)}visit(parsed);
 if(mains.length!==1)throw new Error('This page has no single <main> insertion point. Choose another page or add a main element in the file editor first.');
 const imported=`\nimport ${component} from '${'../'.repeat(target.split('/').length-1)}${path.replace(/\.tsx$/,'')}';\n`;
 const close=mains[0].closingElement.getStart(parsed);let content=page.content.slice(0,close)+`<${component} />`+page.content.slice(close),importAt=0;
 for(const statement of parsed.statements){if(ts.isExpressionStatement(statement)&&ts.isStringLiteral(statement.expression))importAt=statement.end;else break;}
 content=content.slice(0,importAt)+imported+content.slice(importAt);
 return [...files.map(f=>f===page?{...f,content}:f),{path,content:`export default function ${component}(){return <><style>{${JSON.stringify(css)}}</style><div dangerouslySetInnerHTML={{__html:${JSON.stringify(html)}}}/></>}`}];
}
