import {test} from 'node:test';
import assert from 'node:assert/strict';
import {fullstackTemplate,validateFullstack,acceptanceTests} from '../src/lib/fullstack-project';
import {dependencyContext} from '../src/lib/dependency-context';
import {exportGithubFiles} from '../src/lib/github';
import {sealJobCredential,openJobCredential} from '../src/lib/job-store';
import {checkRuntime} from '../src/lib/runtime-sandbox';
test('controlled runtime supports routes, TSX and packages but rejects install hooks and dependency overrides',()=>{const files=fullstackTemplate();validateFullstack(files);const manifest=JSON.parse(files[0].content);manifest.scripts.postinstall='curl bad';assert.throws(()=>validateFullstack([{...files[0],content:JSON.stringify(manifest)},...files.slice(1)]),/scripts/);const exported=exportGithubFiles({projectId:'test',name:'App',files,sql:'',url:null,key:null});assert.ok(exported.some(f=>f.path==='app/page.tsx'));assert.equal(JSON.parse(exported.find(f=>f.path==='vercel.json')!.content).framework,'nextjs');assert.ok(!exported.some(f=>f.path==='index.html'));});
test('dependency context follows imports and consumers, retaining shared layout and falling back for dynamic imports',()=>{const files=[...fullstackTemplate(),{path:'components/Card.tsx',content:'export const Card=()=>null;'},{path:'app/orders/page.tsx',content:"import {Card} from '../../components/Card';export default Card;"},{path:'app/other/page.tsx',content:'export default function Page(){return null}'}];const c=dependencyContext('Change components/Card.tsx',files);assert.ok(c.files.some(f=>f.path==='app/orders/page.tsx'));assert.ok(!c.files.some(f=>f.path==='app/other/page.tsx'));assert.ok(c.omitted>0);assert.equal(dependencyContext('Change components/Card.tsx',[...files,{path:'lib/dynamic.ts',content:'export const get=(s:string)=>import(s)'}]).files.length,files.length+1);});
test('acceptance requirements need real assertions and cannot navigate off the isolated origin',()=>{const file=(steps:unknown[])=>[{path:'studio.tests.json',content:JSON.stringify({requirements:[{id:'x',description:'Booking confirmation',steps}]})}];assert.throws(()=>acceptanceTests(file([{action:'goto',value:'https://evil.example'},{action:'visible',target:'body'}])));assert.throws(()=>acceptanceTests(file([{action:'goto',value:'/'},{action:'text',target:'body',value:''}])));assert.equal(acceptanceTests(file([{action:'goto',value:'/'},{action:'visible',target:'h1'}])).requirements.length,1);});
test('job credentials use authenticated encryption and reject tampering',()=>{const old=process.env.STUDIO_JOB_ENCRYPTION_KEY;process.env.STUDIO_JOB_ENCRYPTION_KEY='11'.repeat(32);try{const value=sealJobCredential('test-key-never-real');assert.ok(!value.includes('test-key'));assert.equal(openJobCredential(value),'test-key-never-real');const bytes=Buffer.from(value,'base64');bytes[20]^=1;assert.throws(()=>openJobCredential(bytes.toString('base64')));}finally{if(old===undefined)delete process.env.STUDIO_JOB_ENCRYPTION_KEY;else process.env.STUDIO_JOB_ENCRYPTION_KEY=old}});
test('runtime executes generated code as a separate user, denies egress and always stops after compile failure',async()=>{let stopped=false;const policies:unknown[]=[];const app={homeDir:'/home/studioapp',writeFiles:async()=>{},runCommand:async(command:any)=>({exitCode:typeof command==='object'&&command.args?.includes('build')?1:0,stderr:async()=>'fixture compilation error'})};const sandbox={createUser:async()=>app,updateNetworkPolicy:async(p:unknown)=>policies.push(p),stop:async()=>{stopped=true}};const report=await checkRuntime(fullstackTemplate(),false,(async()=>sandbox) as any);assert.equal(report.compiled,false);assert.equal(stopped,true);assert.ok(policies.includes('deny-all'));});
test('benchmark requirements cover multi-page navigation and a real server submission',async()=>{const {benchmarkFixtures}=await import('../scripts/phase-one-fixtures');for(const f of benchmarkFixtures){validateFullstack(f.files);const tests=acceptanceTests(f.files);assert.ok(tests.requirements.some(r=>r.id==='submit'));assert.ok(tests.requirements.some(r=>r.id==='navigation'));const graph=dependencyContext('Update app/page.tsx',f.files);assert.ok(graph.files.some(f=>f.path==='app/api/inquiries/route.ts'));}});
test('live preview starts without repeating production compilation and keeps isolated server running',async()=>{
 const commands:any[]=[];let stopped=false;const app={homeDir:'/home/studioapp',writeFiles:async()=>{},runCommand:async(...args:any[])=>{commands.push(args);return {exitCode:0,stderr:async()=>''}}};const sandbox={createUser:async()=>app,updateNetworkPolicy:async()=>{},runCommand:async()=>({exitCode:0,stderr:async()=>''}),domain:()=> 'https://preview.example',expiresAt:new Date(Date.now()+600000),stop:async()=>{stopped=true}};
 const report=await checkRuntime(fullstackTemplate(),false,(async()=>sandbox) as any,true);assert.equal(report.previewUrl,'https://preview.example');assert.equal(stopped,false);assert.ok(commands.some(c=>c[0]?.args?.includes('dev')));assert.ok(!commands.some(c=>c[0]?.args?.includes('build')));
});
