import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
const owner='11111111-1111-4111-8111-111111111111',editor='22222222-2222-4222-8222-222222222222',viewer='33333333-3333-4333-8333-333333333333',stranger='44444444-4444-4444-8444-444444444444';
test('shared projects enforce verified email, roles, revocation and atomic saves',async()=>{const db=new PGlite();try{
 await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to authenticated;grant execute on function auth.uid() to authenticated;insert into auth.users values('${owner}','owner@test.example',now()),('${editor}','editor@test.example',now()),('${viewer}','viewer@test.example',now()),('${stranger}','outsider@test.example',null);`);
 await db.exec(await readFile(new URL('../supabase/schema.sql',import.meta.url),'utf8'));await db.exec(await readFile(new URL('../supabase/migrations/20260912_project_access.sql',import.meta.url),'utf8'));
 await db.exec(`create role service_role bypassrls;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);create table storage.objects(id uuid default gen_random_uuid(),bucket_id text,name text);alter table storage.objects enable row level security;grant usage on schema storage to authenticated;grant select,insert,update,delete on storage.objects to authenticated;`);
 await db.exec(await readFile(new URL('../supabase/migrations/20260913_studio_storage.sql',import.meta.url),'utf8'));
 const as=async(id:string)=>db.exec(`set role authenticated;set request.jwt.claim.sub='${id}';`);await as(owner);
 const p=(await db.query<{id:string}>(`insert into projects(owner_id,name) values($1,'Shared app') returning id`,[owner])).rows[0].id;
 await db.query(`insert into project_access(project_id,email,role) values($1,'editor@test.example','editor'),($1,'viewer@test.example','viewer'),($1,'outsider@test.example','editor')`,[p]);
 await db.query(`insert into project_drafts(project_id,user_id,prompt) values($1,$2,'Owner private draft')`,[p,owner]);
 const objectName=`5511/projects/${p}/revisions/22222222-2222-4222-8222-222222222222.json`;
 await db.query(`insert into storage.objects(bucket_id,name) values('studio-projects',$1)`,[objectName]);
 await assert.rejects(db.query('select * from studio_usage_ledgers'),/permission denied/);
 await as(editor);assert.equal((await db.query('select * from storage.objects')).rows.length,1);
 assert.equal((await db.query(`update storage.objects set name='overwrite' returning *`)).rows.length,0);
 await assert.rejects(db.query(`insert into storage.objects(bucket_id,name) values('studio-projects','5511/projects/------------------------------------/revisions/22222222-2222-4222-8222-222222222222.json')`),/row-level security/);
 assert.equal((await db.query('select * from project_drafts')).rows.length,0);await db.query(`insert into project_drafts(project_id,user_id,prompt) values($1,$2,'Editor draft')`,[p,editor]);await assert.rejects(db.query(`insert into project_drafts(project_id,user_id,prompt) values($1,$2,'Impersonated draft')`,[p,viewer]),/row-level security/);assert.equal((await db.query('select * from projects')).rows.length,1);assert.equal((await db.query('select * from project_access')).rows.length,0);
 await assert.rejects(db.query(`update projects set owner_id=$1 where id=$2`,[editor,p]),/ownership/);
 await assert.rejects(db.query(`insert into project_access(project_id,email,role) values($1,'intruder@test.example','editor')`,[p]),/row-level security/);
 const revision=(await db.query<{r:{id:string}}>(`select save_project_revision($1,null,'Direct text edit','[{"path":"index.html","content":"<h1>Shared</h1>"}]','',0) r`,[p])).rows[0].r;
 await assert.rejects(db.query(`select save_project_revision($1,null,'Stale','[]','',0)`,[p]),/Project changed/);
 await as(viewer);await assert.rejects(db.query(`insert into storage.objects(bucket_id,name) values('studio-projects',$1)`,[objectName]),/row-level security/);assert.equal((await db.query('select * from project_drafts')).rows.length,0);assert.equal((await db.query('select * from revisions')).rows.length,1);await assert.rejects(db.query('select begin_generation($1)',[p]),/not allowed/);await assert.rejects(db.query(`select save_project_revision($1,$2,'Denied','[]','',0)`,[p,revision.id]),/not allowed/);
 await as(stranger);assert.equal((await db.query('select * from storage.objects')).rows.length,0);assert.equal((await db.query('select * from projects')).rows.length,0);
 await as(editor);const run=(await db.query<{id:string}>('select begin_generation($1) id',[p])).rows[0].id;
 await as(owner);await assert.rejects(db.query('select begin_generation($1)',[p]),/Build running/);await db.query(`delete from project_access where project_id=$1 and email='editor@test.example'`,[p]);
 await as(editor);assert.equal((await db.query('select * from projects')).rows.length,0);await assert.rejects(db.query(`select finish_generation($1,'Build','Built','[]','',10,'Shared',$2)`,[run,revision.id]),/access was removed/);
 }finally{await db.close()}});
