import {NextResponse} from 'next/server';
import {z} from 'zod';
import {authorize,ownedProject,failure,readBody,HttpError} from '@/lib/server';
import {requireSameOrigin} from '@/lib/credentials';
import {requireEditor} from '@/lib/project-access';
import {storageConfigured,backupRevision,hasBackup,readBackup} from '@/lib/project-storage';
export const maxDuration=300;
export async function GET(request:Request,ctx:{params:Promise<{id:string}>}){try{const {db}=await authorize(request);const {id}=await ctx.params;const project=await ownedProject(db,id);const configured=storageConfigured();const saved=configured&&project.current_revision_id?await hasBackup(db,id,project.current_revision_id):false;return NextResponse.json({configured,saved},{headers:{'Cache-Control':'no-store'}})}catch(e){return failure(e)}}
export async function POST(request:Request,ctx:{params:Promise<{id:string}>}){try{requireSameOrigin(request);const {db,user}=await authorize(request);const {id}=await ctx.params;await requireEditor(db,id,user.id);const project=await ownedProject(db,id);if(!storageConfigured())throw new HttpError(503,'Configure the Studio Supabase connection first.');const input=z.object({action:z.enum(['backup','restore']),revisionId:z.uuid().optional(),expectedRevision:z.uuid().optional()}).parse(await readBody(request));
 if(input.action==='backup'){const {data:revisions,error}=await db.from('revisions').select('*').eq('project_id',id).order('created_at',{ascending:false}).limit(100);if(error)throw error;let saved=0;for(const revision of revisions??[]){if(await hasBackup(db,id,revision.id)){saved++;continue}const result=await backupRevision(db,project,revision);if(result.state!=='saved')throw new HttpError(502,`${saved} versions backed up. ${result.message}`);saved++;}return NextResponse.json({saved,message:`${saved} most recent versions are stored in Supabase Storage.`})}
 if(!input.revisionId||!input.expectedRevision)throw new HttpError(400,'Choose a version and reopen the project before restoring.');const {data:existing}=await db.from('revisions').select('id').eq('id',input.revisionId).eq('project_id',id).single();if(!existing)throw new HttpError(404,'Version not found.');const backup=await readBackup(db,id,input.revisionId);const {data:revision,error}=await db.rpc('save_project_revision',{p_project:id,p_expected:input.expectedRevision,p_prompt:'Restored saved version from Supabase Storage',p_files:backup.files,p_sql:backup.sql,p_tokens:0});if(error)throw new HttpError(409,'Project changed, or the team migration is not active. Reopen before restoring.');return NextResponse.json({...revision,storage:await backupRevision(db,project,revision)});
 }catch(e){return failure(e)}}
