'use client';
import {useState,useEffect} from 'react';
import Link from 'next/link';
import {browserDb} from '@/lib/supabase';
import {browserWorkspace} from '@/lib/browser-workspace';
import {loadDraft} from '@/lib/drafts';
import type {Project,Revision} from '@/lib/types';
export default function CloudWorkspaceSettings(){
 const [signedIn,setSignedIn]=useState(false),[projects,setProjects]=useState<Project[]>([]),[busy,setBusy]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const offline=async()=>{throw new Error('No provider request for a local project copy.')};
 useEffect(()=>{browserDb()?.auth.getSession().then(({data})=>setSignedIn(!!data.session));browserWorkspace('/api/projects','GET',undefined,offline).then(data=>setProjects(data as Project[])).catch(e=>setError(e.message))},[]);
 async function copy(p:Project){setBusy(p.id);setError('');try{const data=await browserWorkspace('/api/projects/'+p.id,'GET',undefined,offline) as {revisions:Revision[]},current=data.revisions.find((r:any)=>r.id===p.current_revision_id);const auth=await browserDb()?.auth.getSession();if(!auth?.data.session)throw new Error('Sign in to your cloud workspace first.');const headers={'Content-Type':'application/json',Authorization:'Bearer '+auth.data.session.access_token};const r=await fetch('/api/projects/import',{method:'POST',headers,body:JSON.stringify({id:p.id,specification:p.specification,name:p.name,description:p.description,url:p.supabase_url,key:p.supabase_key,revision:current?{files:current.files,sql:current.sql,tokens:current.tokens}:null})});const result=await r.json();if(!r.ok)throw new Error(result.error);if(!result.existing){const draft=await loadDraft('browser:'+p.id);const saved=await fetch(`/api/projects/${p.id}/draft`,{method:'PUT',headers,body:JSON.stringify(draft)});if(!saved.ok)throw new Error('Project copied, but its pending draft was not uploaded. Your browser draft is unchanged.');}setNotice(result.existing?'This project is already in your cloud workspace.':`Current version of ${p.name} copied to the cloud. Browser history is retained on this device.`)}catch(e){setError((e as Error).message)}finally{setBusy('')}}
 return <section className="settings-card"><h2>Employee workspace</h2><p>Each employee signs in with their own email. Project owners choose who can edit or view each project from Team &amp; storage.</p>{!signedIn?<Link className="primary-button" href="/?signin=1">Sign in / create your account</Link>:<><p>You’re signed in. Cloud projects can be opened from another machine using the same Studio website.</p><h3>Copy browser projects to the cloud</h3><p>Copy the current saved version and pending draft. Full browser history stays on this device. Existing cloud projects are not overwritten.</p>{projects.map(p=><div className="team-member" key={p.id}><span>{p.name}</span><button className="subtle-button" disabled={!!busy} onClick={()=>copy(p)}>{busy===p.id?'Copying…':'Copy to cloud'}</button></div>)}{!projects.length&&<p>No browser projects on this device.</p>}</>}
<p className="settings-help">The localhost address only works on this Mac. Deploy Studio to a shared HTTPS address for employees on different computers. Each employee connects their own OpenAI and GitHub credentials; your saved browser keys are not shared.</p>{error&&<p className="settings-error" role="alert">{error}</p>}{notice&&<p className="settings-notice" role="status">{notice}</p>}</section>
}
