'use client';
import {useEffect,useState} from 'react';
import type {SourceFile} from '@/lib/types';
import {isFullstack} from '@/lib/fullstack-project';
import {htmlDesignElements,applyHtmlDesignChange} from '@/lib/design-html';
import {styleProperties,type DesignElement,type DesignChange} from '@/lib/design-types';
type Props={files:SourceFile[];selected:string;onSelect:(id:string)=>void;onChange:(files:SourceFile[])=>void;onSave:()=>void;onCancel:()=>void;saving:boolean;dirty:boolean;onUndo:()=>void;onRedo:()=>void;canUndo:boolean;canRedo:boolean};
export default function DesignInspector(p:Props){const [elements,setElements]=useState<DesignElement[]>([]),[property,setProperty]=useState<DesignChange['property']>('text'),[value,setValue]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function inspect(change?:DesignChange){const r=await fetch('/api/design/source',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({files:p.files,change})});const result=await r.json();if(!r.ok)throw new Error(result.error);return result;}
 useEffect(()=>{let alive=true;setError('');if(isFullstack(p.files)){inspect().then(d=>{if(alive)setElements(d.elements)}).catch(e=>{if(alive)setError(e.message)})}else setElements(htmlDesignElements(p.files));return()=>{alive=false}},[p.files]);
 const selected=elements.find(e=>e.id===p.selected);
 useEffect(()=>{setValue(selected?(property==='text'?selected.text??'':selected.attributes[property]??selected.styles[property]??''):'')},[selected,property]);
 return <aside className="design-inspector" aria-label="Design inspector"><h3>Edit design</h3><p>Click an element in the preview or choose it below. Changes save as a new version. No AI tokens.</p>{isFullstack(p.files)&&<p className="settings-help">The runtime shows the last saved version. After changing the draft, use the element list for further edits. Save and relaunch to preview your changes.</p>}<label>Element<select value={selected?.id??''} onChange={e=>p.onSelect(e.target.value)}><option value="">Select an element</option>{elements.map(e=><option value={e.id} key={e.id}>{e.tag} · {e.label} · {e.path}</option>)}</select></label>{selected&&<><label>Property<select value={property} onChange={e=>setProperty(e.target.value as DesignChange['property'])}><option value="text" disabled={selected.text===null}>Text</option>{selected.tag==='a'&&<option value="href">Link destination</option>}{selected.tag==='img'&&<><option value="src">Image URL</option><option value="alt">Image description</option></>}{styleProperties.map(k=><option key={k} value={k} disabled={!selected.styleEditable}>{k.replace(/([A-Z])/g,' $1')}</option>)}</select></label><label>Value<textarea value={value} onChange={e=>setValue(e.target.value)} maxLength={property==='text'?10000:property==='alt'?1000:2000}/></label><button className="subtle-button" disabled={busy||p.saving||(property==='text'&&selected.text===null)} onClick={async()=>{setBusy(true);setError('');try{const change={id:selected.id,property,value};p.onChange(isFullstack(p.files)?(await inspect(change)).files:applyHtmlDesignChange(p.files,change));}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>Apply to draft</button></>}{error&&<p role="alert" className="settings-error">{error}</p>}<div className="settings-actions"><button disabled={!p.canUndo||busy||p.saving} onClick={p.onUndo}>Undo</button><button disabled={!p.canRedo||busy||p.saving} onClick={p.onRedo}>Redo</button></div><button className="primary-button" disabled={!p.dirty||busy||p.saving} onClick={p.onSave}>{p.saving?'Saving…':'Save design version'}</button><button className="subtle-button" disabled={busy||p.saving} onClick={p.onCancel}>Close / discard draft</button></aside>;
}
