'use client';
import {useState} from 'react';
import type {Project,Revision} from '@/lib/types';
import type {DesignAudit} from '@/lib/design-bridge';
import type {ImageAttachment} from '@/lib/attachments';
import ImageAttachments from './image-attachments';
type Review={summary:string;findings:{priority:string;area:string;evidence:string;recommendation:string}[]};
export default function DesignReview({project,revision,audit,onAudit,onClose,onFix}:{project:Project;revision:Revision;audit:DesignAudit|null;onAudit:()=>void;onClose:()=>void;onFix:(prompt:string)=>void}){
 const [images,setImages]=useState<ImageAttachment[]>([]),[processing,setProcessing]=useState(false),[review,setReview]=useState<Review|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[usage,setUsage]=useState(''),[chosen,setChosen]=useState<string[]>([]);
 const findings=[...(audit?.findings.map((f,i)=>({id:'audit-'+i+': '+f.element+': '+f.message,label:f.category+' · '+f.element,detail:f.message,fix:f.fix}))??[]),...(review?.findings.map((f,i)=>({id:'ai-'+i,label:f.priority+' · '+f.area,detail:f.evidence,fix:f.recommendation}))??[])];
 return <div className="modal-backdrop"><section className="modal phase-two-modal" role="dialog" aria-modal="true" aria-label="Design review"><h2>Design review</h2><p>Review the current viewport, then turn selected findings into a build request. Nothing changes automatically.</p><button className="subtle-button" onClick={onAudit}>Check visible preview · free</button>{audit?<p>{audit.viewport.width} × {audit.viewport.height} · {audit.findings.length} findings · advisory checks for contrast, layout, labels and image loading.</p>:<p>Open Preview first. Next.js apps need a running saved preview. Check desktop and mobile separately.</p>}
 <h3>Optional AI visual critique</h3>{project.id==='example'&&<p>Save your own project to run an AI review. The example supports free design checks.</p>}<p>Add a screenshot of the current app first, then up to two reference images. The review uses your OpenAI budget; it does not rebuild the app.</p><ImageAttachments images={images} onChange={setImages} onError={setError} onProcessing={setProcessing} disabled={busy}><div className="review-drop">Drop current screenshot here, followed by design references.</div></ImageAttachments><button className="primary-button" disabled={busy||processing||!images.length||project.id==='example'} onClick={async()=>{setBusy(true);setError('');try{const r=await fetch('/api/design/review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requestId:crypto.randomUUID(),projectId:project.id,name:project.name,brief:JSON.stringify(project.specification??{purpose:project.description}),observations:JSON.stringify(audit??{}),images})});const d=await r.json();if(!r.ok)throw new Error(d.error);setReview(d.review);setUsage(d.reused?'Reused review · 0 new tokens':`${d.usage?.total?.toLocaleString()??'Unknown'} tokens · ${d.costUsd==null?'cost pending':'$'+d.costUsd.toFixed(4)}`);}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>{busy?'Reviewing…':'Run AI review · uses token budget'}</button><p className="settings-help">Uses GPT-5.4 mini, at most 4,000 output tokens, your existing budget limits and no automatic retries. {usage}</p>{review&&<p>{review.summary}</p>}{error&&<p role="alert" className="settings-error">{error}</p>}
 <div className="review-findings">{findings.map(f=><article key={f.id}><label><input type="checkbox" checked={chosen.includes(f.id)} onChange={e=>setChosen(old=>e.target.checked?[...old,f.id]:old.filter(id=>id!==f.id))}/><b>{f.label}</b></label><p>{f.detail}</p><p>{f.fix}</p></article>)}</div><div className="settings-actions"><button className="primary-button" disabled={!chosen.length||busy||project.access_role==='viewer'} onClick={()=>{onFix(('Improve this saved design while preserving its working features. Review findings are advisory; verify each before changing code.\n'+findings.filter(f=>chosen.includes(f.id)).map(f=>`${f.label}: ${f.detail} Suggested fix: ${f.fix}`).join('\n')).slice(0,6000));onClose()}}>Add selected fixes to chat</button><button className="subtle-button" disabled={busy} onClick={()=>{const blob=new Blob([JSON.stringify({revision:revision.id,audit,review},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='design-review.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}>Download review</button><button className="subtle-button" disabled={busy} onClick={onClose}>Close</button></div></section></div>;
}
