'use client';
import {designAuditSchema} from '@/lib/design-types';
import {useEffect,useRef,useState} from 'react';
import type {DesignAudit} from '@/lib/design-bridge';
export default function FullstackPreview({projectId,revisionId,building=false,api,selecting=false,onSelect,onAudit,auditRequest=0}:{projectId:string;revisionId:string;building?:boolean;api:(p:string,m?:string,b?:unknown)=>Promise<any>;selecting?:boolean;onSelect?:(id:string)=>void;onAudit?:(report:DesignAudit)=>void;auditRequest?:number}){
 const [preview,setPreview]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const frame=useRef<HTMLIFrameElement>(null),callbacks=useRef({onSelect,onAudit});callbacks.current={onSelect,onAudit};
 const apiRef=useRef(api);apiRef.current=api;const attempt=useRef('');const launching=useRef(false);
 async function openPreview(){if(launching.current||building)return;launching.current=true;attempt.current=revisionId;setBusy(true);setError('');try{const next=await apiRef.current(`/api/projects/${projectId}/preview`,'POST',{});setPreview({...next,revisionId});}catch(e){setError((e as Error).message)}finally{launching.current=false;setBusy(false)}}
 useEffect(()=>{if(preview&&preview.revisionId!==revisionId&&!building&&attempt.current!==revisionId)void openPreview();},[revisionId,building,preview?.revisionId]);
 function send(action:string){if(preview)frame.current?.contentWindow?.postMessage({channel:preview.designChannel,action,enabled:selecting},new URL(preview.previewUrl).origin);}
 useEffect(()=>{send('select-mode')},[selecting,preview]);useEffect(()=>{if(auditRequest)send('audit')},[auditRequest]);
 useEffect(()=>{if(!preview)return;const listener=(e:MessageEvent)=>{if(e.source!==frame.current?.contentWindow||e.origin!==new URL(preview.previewUrl).origin||e.data?.channel!==preview.designChannel||e.data?.kind!=='studio-design')return;if(typeof e.data.selected==='string')callbacks.current.onSelect?.(e.data.selected.slice(0,220));const report=designAuditSchema.safeParse(e.data.report);if(report.success)callbacks.current.onAudit?.(report.data);};window.addEventListener('message',listener);return()=>window.removeEventListener('message',listener)},[preview]);
 return <><div className="preview-recovery"><span>Preview session · 10 minutes · No AI tokens · Vercel compute charges apply</span><button disabled={busy||building} onClick={()=>void openPreview()}>{busy?'Updating preview…':building?'Waiting for saved changes…':preview?'Restart preview':'Open preview'}</button></div>{error&&<p role="alert">{error}</p>}{preview?<iframe ref={frame} onLoad={()=>send('select-mode')} title="Full-stack application preview" sandbox="allow-scripts allow-forms allow-same-origin" referrerPolicy="no-referrer" src={preview.previewUrl}/>:<p className="settings-notice">Your saved app is ready to preview. Click Open preview to explore its pages and features. This test session does not connect to your production database.</p>}</>;
}
