'use client';
import type {PreviewState} from '@/lib/build-display';
import BuildTheater from './build-theater';
import {designAuditSchema} from '@/lib/design-types';
import {useEffect,useRef,useState} from 'react';
import type {DesignAudit} from '@/lib/design-bridge';
const sessions=new Map<string,any>();
const pendingPreviews=new Map<string,Promise<any>>();
export default function FullstackPreview({projectId,revisionId,building=false,api,selecting=false,onSelect,onAudit,auditRequest=0,onState}:{projectId:string;revisionId:string;building?:boolean;api:(p:string,m?:string,b?:unknown)=>Promise<any>;selecting?:boolean;onSelect?:(id:string)=>void;onAudit?:(report:DesignAudit)=>void;auditRequest?:number;onState?:(revisionId:string,state:PreviewState)=>void}){
 const [preview,setPreview]=useState<any>(()=>{const saved=sessions.get(projectId);return saved&&Date.parse(saved.expiresAt)>Date.now()+30000?saved:null}),[busy,setBusy]=useState(false),[error,setError]=useState('');const frame=useRef<HTMLIFrameElement>(null),callbacks=useRef({onSelect,onAudit});callbacks.current={onSelect,onAudit};
 const [loadedUrl,setLoadedUrl]=useState('');const stateCallback=useRef(onState);stateCallback.current=onState;
 const state:PreviewState=error?'error':busy||preview?.revisionId!==revisionId||loadedUrl!==preview?.previewUrl?'loading':'ready';
 useEffect(()=>{stateCallback.current?.(revisionId,state)},[revisionId,state]);
 const apiRef=useRef(api);apiRef.current=api;const attempt=useRef(preview?.revisionId??'');const launching=useRef(false);
 async function openPreview(){if(launching.current||building)return;launching.current=true;attempt.current=revisionId;setBusy(true);setError('');setLoadedUrl('');try{const key=`${projectId}:${revisionId}`;let pending=pendingPreviews.get(key);if(!pending){pending=apiRef.current(`/api/projects/${projectId}/preview`,'POST',{});pendingPreviews.set(key,pending);}let next;try{next=await pending;}finally{if(pendingPreviews.get(key)===pending)pendingPreviews.delete(key);}const saved={...next,revisionId};sessions.set(projectId,saved);setPreview(saved);}catch(e){setError((e as Error).message)}finally{launching.current=false;setBusy(false)}}
 useEffect(()=>{if(building)return;if(!building&&!busy&&attempt.current!==revisionId)void openPreview();},[revisionId,building,busy]);
 useEffect(()=>{if(!preview||building)return;const delay=Math.max(1000,Date.parse(preview.expiresAt)-Date.now()-30000);const timer=setTimeout(()=>{attempt.current='';void openPreview();},delay);return()=>clearTimeout(timer)},[preview,building]);
 function send(action:string){if(preview)frame.current?.contentWindow?.postMessage({channel:preview.designChannel,action,enabled:selecting},new URL(preview.previewUrl).origin);}
 useEffect(()=>{send('select-mode')},[selecting,preview]);useEffect(()=>{if(auditRequest)send('audit')},[auditRequest]);
 useEffect(()=>{if(!preview)return;const listener=(e:MessageEvent)=>{if(e.source!==frame.current?.contentWindow||e.origin!==new URL(preview.previewUrl).origin||e.data?.channel!==preview.designChannel||e.data?.kind!=='studio-design')return;if(typeof e.data.selected==='string')callbacks.current.onSelect?.(e.data.selected.slice(0,220));const report=designAuditSchema.safeParse(e.data.report);if(report.success)callbacks.current.onAudit?.(report.data);};window.addEventListener('message',listener);return()=>window.removeEventListener('message',listener)},[preview]);
 return <><div className="preview-recovery"><span>{building?'Finishing build checks · Showing the previously loaded preview':state==='loading'?'Updating preview · Your saved changes are not visible yet':state==='error'?'Preview update failed · Your saved changes are preserved':'Latest saved preview loaded'} · No AI tokens · Vercel compute applies</span><button disabled={busy||building} onClick={()=>void openPreview()}>{busy?'Updating preview…':building?'Finishing checks…':preview?'Refresh preview':'Retry preview'}</button></div>{error&&<p role="alert">{error}</p>}{preview?<iframe ref={frame} onLoad={()=>{setLoadedUrl(preview.previewUrl);send('select-mode')}} onError={()=>setError('Preview could not load. Retry the preview.')} title="Full-stack application preview" sandbox="allow-scripts allow-forms allow-same-origin" referrerPolicy="no-referrer" src={preview.previewUrl}/>:<BuildTheater failed={!!error} phase={building?'Building and checking your app…':'Starting your live preview…'}/>}</>;
}
