'use client';
import {designAuditSchema} from '@/lib/design-types';
import {useEffect,useRef,useState} from 'react';
import type {DesignAudit} from '@/lib/design-bridge';
const sessions=new Map<string,any>();
export default function FullstackPreview({projectId,revisionId,building=false,api,selecting=false,onSelect,onAudit,auditRequest=0}:{projectId:string;revisionId:string;building?:boolean;api:(p:string,m?:string,b?:unknown)=>Promise<any>;selecting?:boolean;onSelect?:(id:string)=>void;onAudit?:(report:DesignAudit)=>void;auditRequest?:number}){
 const [preview,setPreview]=useState<any>(()=>{const saved=sessions.get(projectId);return saved&&Date.parse(saved.expiresAt)>Date.now()+30000?saved:null}),[busy,setBusy]=useState(false),[error,setError]=useState('');const frame=useRef<HTMLIFrameElement>(null),callbacks=useRef({onSelect,onAudit});callbacks.current={onSelect,onAudit};
 const apiRef=useRef(api);apiRef.current=api;const attempt=useRef(preview?.revisionId??'');const launching=useRef(false);
 async function openPreview(){if(launching.current||building)return;launching.current=true;attempt.current=revisionId;setBusy(true);setError('');try{const next=await apiRef.current(`/api/projects/${projectId}/preview`,'POST',{});const saved={...next,revisionId};sessions.set(projectId,saved);setPreview(saved);}catch(e){setError((e as Error).message)}finally{launching.current=false;setBusy(false)}}
 useEffect(()=>{if(building){attempt.current='';return;}if(!building&&!busy&&attempt.current!==revisionId)void openPreview();},[revisionId,building,busy]);
 useEffect(()=>{if(!preview||building)return;const delay=Math.max(1000,Date.parse(preview.expiresAt)-Date.now()-30000);const timer=setTimeout(()=>{attempt.current='';void openPreview();},delay);return()=>clearTimeout(timer)},[preview,building]);
 function send(action:string){if(preview)frame.current?.contentWindow?.postMessage({channel:preview.designChannel,action,enabled:selecting},new URL(preview.previewUrl).origin);}
 useEffect(()=>{send('select-mode')},[selecting,preview]);useEffect(()=>{if(auditRequest)send('audit')},[auditRequest]);
 useEffect(()=>{if(!preview)return;const listener=(e:MessageEvent)=>{if(e.source!==frame.current?.contentWindow||e.origin!==new URL(preview.previewUrl).origin||e.data?.channel!==preview.designChannel||e.data?.kind!=='studio-design')return;if(typeof e.data.selected==='string')callbacks.current.onSelect?.(e.data.selected.slice(0,220));const report=designAuditSchema.safeParse(e.data.report);if(report.success)callbacks.current.onAudit?.(report.data);};window.addEventListener('message',listener);return()=>window.removeEventListener('message',listener)},[preview]);
 return <><div className="preview-recovery"><span>Live preview · Updates after saved changes · No AI tokens · Vercel compute applies</span><button disabled={busy||building} onClick={()=>void openPreview()}>{busy?'Updating preview…':building?'Waiting for saved changes…':preview?'Refresh preview':'Retry preview'}</button></div>{error&&<p role="alert">{error}</p>}{preview?<iframe ref={frame} onLoad={()=>send('select-mode')} title="Full-stack application preview" sandbox="allow-scripts allow-forms allow-same-origin" referrerPolicy="no-referrer" src={preview.previewUrl}/>:<p className="settings-notice">Preparing your live preview… Your saved changes will appear here automatically.</p>}</>;
}
