'use client';
import {useState,useEffect} from 'react';
import {Github} from 'lucide-react';
export default function GithubSettings(){
 const [status,setStatus]=useState({connected:false,login:'',oauth:false}),[token,setToken]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 async function refresh(){const r=await fetch('/api/github',{cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error);setStatus(data)}
 useEffect(()=>{refresh().catch(e=>setError(e.message));const query=new URLSearchParams(window.location.search);if(query.get('github_error'))setError(query.get('github_error')!);if(query.has('github_connected'))setNotice('GitHub connected.')},[]);
 async function connect(remove=false){setBusy(true);setError('');try{const r=await fetch('/api/github',{method:remove?'DELETE':'POST',headers:{'Content-Type':'application/json'},...(!remove?{body:JSON.stringify({token})}:{})});const data=await r.json();if(!r.ok)throw new Error(data.error);setToken('');await refresh();setNotice(remove?'GitHub disconnected from Studio.':'GitHub connected. Choose a repository inside each project.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function signin(){setBusy(true);setError('');try{const r=await fetch('/api/github/oauth/start',{method:'POST'});const data=await r.json();if(!r.ok)throw new Error(data.error);window.location.assign(data.url)}catch(e){setError((e as Error).message);setBusy(false)}}
 return <section className="settings-card"><div className="settings-card-title"><Github size={28}/><div><h2>GitHub</h2><p>One account · A repository for each project</p></div><span className={status.connected?'connection-ready':'tag'}>{status.connected?'@'+status.login:'Not connected'}</span></div><p>Publish saved app versions to GitHub. Connect each repository to Vercel for automatic deployments.</p><div className="settings-actions"><button className="primary-button" disabled={busy||!status.oauth} onClick={signin}>Sign in with GitHub</button>{status.connected&&<button className="subtle-button" disabled={busy} onClick={()=>connect(true)}>Disconnect GitHub</button>}</div>
 {!status.oauth&&<details className="github-setup"><summary>Set up GitHub browser sign-in</summary><p>Create an OAuth app in GitHub → Settings → Developer settings → OAuth Apps. Set its homepage to your Studio address and callback to <code>/api/github/oauth/callback</code> on that same address.</p><p>For this local Studio, use <code>http://127.0.0.1:3001/api/github/oauth/callback</code>. Add these server settings and restart Studio:</p><pre>GITHUB_CLIENT_ID=your_client_id{'\n'}GITHUB_CLIENT_SECRET=your_client_secret{'\n'}GITHUB_REDIRECT_URI=http://127.0.0.1:3001/api/github/oauth/callback</pre><p>For deployment, use your HTTPS Studio domain. Keep the secret server-side. OAuth requests repository access; use a scoped token below if you prefer selecting repositories yourself.</p><a href="https://github.com/settings/applications/new" target="_blank" rel="noreferrer">Register a GitHub OAuth app ↗</a></details>}
 <form onSubmit={e=>{e.preventDefault();void connect()}}><label htmlFor="github-token">Or connect with a GitHub access token</label><input id="github-token" type="password" autoComplete="off" value={token} onChange={e=>setToken(e.target.value)} placeholder="Paste a GitHub token" required minLength={10}/><p className="settings-help">For existing repositories, use a fine-grained token with Contents: read and write, and access to those repositories. Creating repositories also requires Administration: write and access covering new repositories. A classic token with repo scope is another option. Organization policies may require approval.</p><div className="settings-actions"><button className="subtle-button" disabled={busy||!token.trim()}>{busy?'Connecting…':'Connect GitHub token'}</button><a href="https://github.com/settings/personal-access-tokens/new" target="_blank" rel="noreferrer">Create a token ↗</a></div></form><p className="settings-help">Your credential stays in an HTTP-only cookie in this browser, expires after at most 30 days, and is never sent to the AI or included in source. Disconnecting removes it from Studio; revoke it in GitHub to invalidate it everywhere.</p>{error&&<p className="settings-error" role="alert">{error}</p>}{notice&&<p className="settings-notice" role="status">{notice}</p>}</section>
}
