'use client';
import {useRef,useState,useEffect} from 'react';
import {ImagePlus,X} from 'lucide-react';
import {prepareImage,type ImageAttachment} from '@/lib/attachments';
export default function ImageAttachments({images,onChange,onError,onProcessing,disabled,children}:{images:ImageAttachment[];onChange:(images:ImageAttachment[])=>void;onError:(message:string)=>void;onProcessing:(value:boolean)=>void;disabled:boolean;children:React.ReactNode}){
 const zone=useRef<HTMLDivElement>(null);const input=useRef<HTMLInputElement>(null),pending=useRef(false);const [drag,setDrag]=useState(false),[processing,setProcessing]=useState(false);
 async function add(files:File[]){if(disabled||pending.current)return;if(images.length+files.length>3){onError('Attach up to 3 images per message.');return}pending.current=true;setProcessing(true);onProcessing(true);try{const ready=[];for(const file of files)ready.push(await prepareImage(file));onChange([...images,...ready])}catch(e){onError((e as Error).message)}finally{pending.current=false;setProcessing(false);onProcessing(false)}}
 useEffect(()=>{const panel=zone.current?.closest('.chat-panel');if(!panel)return;const over=(event:Event)=>{const e=event as DragEvent;if(e.dataTransfer?.types.includes('Files')){e.preventDefault();setDrag(true)}};const drop=(event:Event)=>{const e=event as DragEvent;e.preventDefault();e.stopPropagation();setDrag(false);void add(Array.from(e.dataTransfer?.files??[]))};panel.addEventListener('dragover',over);panel.addEventListener('drop',drop);return()=>{panel.removeEventListener('dragover',over);panel.removeEventListener('drop',drop)}},[images,disabled]);
 return <div ref={zone} className={`attachment-zone ${drag?'is-dragging':''}`} onDragOver={e=>{if(e.dataTransfer.types.includes('Files')){e.preventDefault();setDrag(true)}}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setDrag(false)}} onDrop={e=>{e.preventDefault();setDrag(false);void add(Array.from(e.dataTransfer.files))}} onPaste={e=>{const files=Array.from(e.clipboardData.files);if(files.length){e.preventDefault();void add(files)}}}>
 {drag&&<div className="drop-label">Drop images for design context</div>}{children}
 <div className="attachment-tools"><input ref={input} type="file" accept="image/png,image/jpeg,image/webp" multiple hidden onChange={e=>{void add(Array.from(e.target.files??[]));e.target.value=''}}/><button type="button" className="subtle-button" onClick={()=>input.current?.click()} disabled={disabled||processing||images.length>=3}><ImagePlus size={15}/>{processing?'Preparing images…':'Add images'}</button><small>Drop or paste · {images.length}/3 · Sent with this message</small></div>
 {!!images.length&&<div className="attachment-list">{images.map((image,i)=><div key={image.name+i}><img src={image.dataUrl} alt={image.name}/><span>{image.name}</span><button type="button" aria-label={`Remove ${image.name}`} disabled={disabled||processing} onClick={()=>onChange(images.filter((_,n)=>n!==i))}><X size={14}/></button></div>)}</div>}
 </div>
}
