'use client';
import {useState,useRef} from 'react';
import {prepareImage,type ImageAttachment} from '@/lib/attachments';
export default function ImageEditor({image,onApply,onClose,onProcessing}:{image:ImageAttachment;onApply:(image:ImageAttachment)=>void;onClose:()=>void;onProcessing:(busy:boolean)=>void}){
 const [prompt,setPrompt]=useState(''),[result,setResult]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[cost,setCost]=useState<number|null>(null);const pending=useRef(false);
 async function edit(){if(pending.current)return;pending.current=true;setBusy(true);onProcessing(true);setError('');try{const response=await fetch('/api/images/edit',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image,prompt,requestId:crypto.randomUUID()})});const value=await response.json();if(!response.ok)throw new Error(value.error||'Image edit failed.');setResult(value.dataUrl);setCost(value.costUsd??null);}catch(e){setError((e as Error).message)}finally{pending.current=false;setBusy(false);onProcessing(false)}}
 async function apply(){setBusy(true);onProcessing(true);try{const b64=result.split(',')[1],bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));onApply(await prepareImage(new File([bytes],image.name.replace(/\.[^.]+$/,'')+'-edited.webp',{type:'image/webp'})));}catch(e){setError((e as Error).message)}finally{setBusy(false);onProcessing(false)}}
 return <section className="image-editor" aria-label="Edit uploaded image"><strong>Edit image</strong><p>The original stays attached. Review the edited copy before adding it.</p><div className="image-comparison"><figure><img src={image.dataUrl} alt="Original uploaded image"/><figcaption>Original</figcaption></figure>{result&&<figure><img src={result} alt="Edited image preview"/><figcaption>Edited copy</figcaption></figure>}</div><label>What should change?<textarea value={prompt} disabled={busy} onChange={e=>setPrompt(e.target.value)} maxLength={1000} placeholder="For example: remove the background while preserving the logo and lettering"/></label><small>AI image edit · records a $0.96 estimated allowance; actual usage is recorded afterward. AI edits can alter lettering—use the original for an exact logo.</small>{error&&<p role="alert">{error}</p>}<div><button type="button" className="subtle-button" disabled={busy||prompt.trim().length<5} onClick={()=>void edit()}>{busy?'Working…':'Create edited copy'}</button>{result&&<><button type="button" className="subtle-button" disabled={busy} onClick={()=>void apply()}>Add edited copy</button><a href={result} download="edited-image.webp">Download</a></>}<button type="button" disabled={busy} onClick={onClose}>Close</button></div>{cost!==null&&<small>Image edit used ${cost.toFixed(4)}.</small>}</section>;
}
