'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {ChevronDown,ChevronRight,Folder,FileCode,Search,Download,Upload,Plus} from 'lucide-react';
import type {SourceFile} from '@/lib/types';
import {validateArtifact} from '@/lib/artifacts';
import {checkFilePath,fileChanges,fileMatches,removeProjectFile,renameProjectFile,requiredFile} from '@/lib/project-files';
import {isFullstack} from '@/lib/fullstack-project';

type Props={files:SourceFile[];readOnly:boolean;onDirty:(dirty:boolean)=>void;onSave:(files:SourceFile[])=>Promise<void>};
export default function ProjectFiles({files,readOnly,onDirty,onSave}:Props){
 const [draft,setDraft]=useState(files),[selected,setSelected]=useState(files[0]?.path??''),[query,setQuery]=useState(''),[contents,setContents]=useState(false),[collapsed,setCollapsed]=useState<Set<string>>(new Set()),[action,setAction]=useState<'create'|'rename'|'delete'|'discard'|null>(null),[path,setPath]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[saving,setSaving]=useState(false);
 const upload=useRef<HTMLInputElement>(null),editor=useRef<HTMLTextAreaElement>(null);
 const changes=useMemo(()=>fileChanges(files,draft),[files,draft]);const dirty=changes.length>0;
 const matches=useMemo(()=>fileMatches(draft,query,contents),[draft,query,contents]);
 const active=draft.find(f=>f.path===selected);const locked=readOnly||saving;
 useEffect(()=>{onDirty(dirty)},[dirty,onDirty]);
 useEffect(()=>{if(!dirty)setDraft(files)},[files,dirty]);
 async function save(){if(locked||!dirty)return;setSaving(true);setError('');try{validateArtifact({name:'Project',summary:'File edits',files:draft,sql:''});await onSave(draft);setNotice('Saved as a new version. No AI tokens used.')}catch(e){setError((e as Error).message)}finally{setSaving(false)}}
 function run(fn:()=>void){setError('');try{fn()}catch(e){setError((e as Error).message)}}
 function begin(next:typeof action){setError('');setPath(next==='rename'?selected:'');setAction(next)}
 function download(){if(!active)return;const url=URL.createObjectURL(new Blob([active.content],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=active.path.split('/').pop()!;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 function select(file:SourceFile){setSelected(file.path);setAction(null);if(contents&&query.trim()){const offset=file.content.toLowerCase().indexOf(query.trim().toLowerCase());if(offset>=0)requestAnimationFrame(()=>{editor.current?.focus();editor.current?.setSelectionRange(offset,offset+query.trim().length)})}}
 function tree(prefix='',depth=0):React.ReactNode{
 const children=new Map<string,boolean>();for(const f of matches){if(!f.path.startsWith(prefix))continue;const rest=f.path.slice(prefix.length),part=rest.split('/')[0];children.set(part,rest.includes('/'))}
 return [...children].sort(([a,af],[b,bf])=>Number(bf)-Number(af)||a.localeCompare(b)).map(([name,folder])=>{const full=prefix+name,open=!!query||!collapsed.has(full);return folder?<div key={full}><button className="file-tree-folder" style={{paddingLeft:12+depth*14}} aria-expanded={open} onClick={()=>setCollapsed(old=>{const n=new Set(old);n.has(full)?n.delete(full):n.add(full);return n})}>{open?<ChevronDown size={14}/>:<ChevronRight size={14}/>}<Folder size={15}/>{name}</button>{open&&tree(full+'/',depth+1)}</div>:<button key={full} title={full} aria-current={selected===full?'page':undefined} className={'file-tree-item '+(selected===full?'active':'')} style={{paddingLeft:26+depth*14}} onClick={()=>select(draft.find(f=>f.path===full)!)}><FileCode size={14}/><span>{name}</span>{changes.some(c=>c.path===full)&&<small aria-label="Unsaved change">●</small>}</button>})
 }
 return <section className="project-files" aria-label="Project files">
 <div className="files-header"><div><b>Project files</b><small>{draft.length} files · {new TextEncoder().encode(draft.map(f=>f.content).join('')).length.toLocaleString()} bytes</small></div><div className="files-actions"><button disabled={locked} onClick={()=>begin('create')}><Plus size={14}/>New file</button><button disabled={locked} onClick={()=>upload.current?.click()}><Upload size={14}/>Import text</button><button disabled={!dirty||locked} onClick={()=>begin('discard')}>Discard</button><button className="primary-button" disabled={!dirty||locked} onClick={()=>void save()}>{saving?'Saving…':'Save version'}</button></div></div>
 <input ref={upload} hidden type="file" multiple onChange={async e=>{const picked=Array.from(e.target.files??[]);e.target.value='';setError('');try{let next=[...draft];for(const f of picked){if(f.size>160000)throw new Error('Import files smaller than 160 KB.');checkFilePath(next,f.name);const content=new TextDecoder('utf-8',{fatal:true}).decode(await f.arrayBuffer());if(content.includes('\0'))throw new Error('Only UTF-8 text source files can be imported.');next.push({path:f.name,content})}validateArtifact({name:'Project',summary:'Import',files:next,sql:''});setDraft(next);if(picked[0])setSelected(picked[0].name)}catch(e){setError((e as Error).message)}}}/>
 {readOnly&&<p className="files-notice">Read-only source. {files.length?'You can browse, search, copy, and download files.':'Build or install a feature to create the first files.'}</p>}
 {dirty&&<div className="files-notice" role="status">{changes.length} unsaved file changes. Save or discard before leaving Files. <details><summary>Review changes</summary>{changes.map(c=><div key={c.path}>{c.kind}: {c.path}</div>)}</details></div>}
 {error&&<p className="settings-error" role="alert">{error}</p>}{notice&&<p className="files-notice" role="status">{notice}</p>}
 {action&&<form className="file-operation" onSubmit={e=>{e.preventDefault();run(()=>{if(action==='create'){checkFilePath(draft,path);if(draft.length>=80)throw new Error('Projects support up to 80 source files.');setDraft([...draft,{path,content:''}]);setSelected(path)}else if(action==='rename'){setDraft(renameProjectFile(draft,selected,path));setSelected(path)}else if(action==='delete'){setDraft(removeProjectFile(draft,selected));setSelected(draft.find(f=>f.path!==selected)?.path??'')}else {setDraft(files);setSelected(files[0]?.path??'')}setAction(null)})}}>
 <b>{action==='create'?'Create a file':action==='rename'?'Rename or move file':action==='delete'?'Delete '+selected+'?':'Discard all unsaved file changes?'}</b>
 {(action==='create'||action==='rename')&&<><label>File path<input autoFocus required maxLength={180} value={path} onChange={e=>setPath(e.target.value)} placeholder={isFullstack(draft)?'components/example.tsx':'components/example.js'}/></label><small>Use / to create folders. Empty folders are not stored. Renaming does not update imports; update references before saving.</small></>}
 <div><button className="primary-button" disabled={locked}>Confirm {action}</button><button type="button" disabled={saving} onClick={()=>setAction(null)}>Cancel</button></div></form>}
 <div className="files-workspace"><aside className="files-directory" aria-label="Files directory"><label className="files-search"><Search size={15}/><input aria-label="Search project files" placeholder="Search files…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="files-content-search"><input type="checkbox" checked={contents} onChange={e=>setContents(e.target.checked)}/>Search inside files</label><div className="files-tree">{tree()}{!matches.length&&<p>{query?'No matching files.':'No files yet.'}</p>}</div><small>{matches.length} of {draft.length} files</small></aside>
 <div className="files-content">{active?<><div className="file-content-toolbar"><b title={active.path}>{active.path}</b><div><button onClick={async()=>{try{await navigator.clipboard.writeText(active.content);setNotice('File copied.')}catch{setError('Clipboard unavailable. Select and copy the source manually.')}}}>Copy</button><button onClick={download} aria-label="Download selected file"><Download size={15}/></button><button disabled={locked||requiredFile(draft,selected)} onClick={()=>begin('rename')}>Rename / move</button><button disabled={locked||requiredFile(draft,selected)} onClick={()=>begin('delete')}>Delete</button></div></div><textarea ref={editor} className="file-source-editor" aria-label={'Source of '+active.path} value={active.content} readOnly={locked} spellCheck={false} autoCapitalize="off" autoCorrect="off" wrap="off" maxLength={160000} onChange={e=>{const content=e.target.value;setDraft(old=>old.map(f=>f.path===selected?{...f,content}:f))}} onKeyDown={e=>{if((e.metaKey||e.ctrlKey)&&e.key==='s'){e.preventDefault();void save()}}}/><div className="file-content-footer">{active.content.split('\n').length.toLocaleString()} lines · {active.content.length.toLocaleString()} characters <span>{readOnly?'Read only':'⌘ / Ctrl S to save · 0 AI tokens'}</span></div></>:<div className="files-empty"><Folder size={32}/><p>Select a file to view its contents.</p></div>}</div></div>
 </section>
}
