'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import type {Project,Revision,SourceFile} from '@/lib/types';
import type {GithubConnection} from '@/lib/github-connection';
import {mergeSources,sameSources} from '@/lib/github-merge';
import {validateArtifact} from '@/lib/artifacts';
import {isFullstack} from '@/lib/fullstack-project';
import SourceChanges from './source-changes';
type Incoming={head:string;base:SourceFile[];remote:SourceFile[];revisionId:string;local:SourceFile[]};
export default function ProjectGithub({project,revision,api,onProject,onSaved,onClose}:{project:Project;revision:Revision;api:(p:string,m?:string,b?:unknown)=>Promise<any>;onProject:(p:Project)=>void;onSaved:(r:Revision)=>void;onClose:()=>void}){
 const [login,setLogin]=useState(''),[connected,setConnected]=useState(false),[dest,setDest]=useState<GithubConnection|null>(project.github_connection??null),[mode,setMode]=useState<'new'|'existing'>('new'),[name,setName]=useState(project.name.toLowerCase().replace(/[^a-z0-9-]/g,'-').slice(0,100)),[repository,setRepository]=useState(''),[branch,setBranch]=useState(''),[privateRepo,setPrivateRepo]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[commit,setCommit]=useState(''),[incoming,setIncoming]=useState<Incoming|null>(null),[choices,setChoices]=useState<Record<string,'local'|'remote'>>({});
 useEffect(()=>{if(!project.github_connection){try{const saved=JSON.parse(localStorage.getItem('5511-github:'+project.id)??'null');if(saved?.repository)setRepository(saved.repository)}catch{}}fetch('/api/github',{cache:'no-store'}).then(async r=>{const s=await r.json();if(!r.ok)throw new Error(s.error);setLogin(s.login);setConnected(s.connected)}).catch(e=>setError(e.message))},[project.id]);
 async function send(path:string,body:unknown){const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);return d;}
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');try{await fn()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function remember(connection:GithubConnection){const p=await api(`/api/projects/${project.id}`,'PATCH',{github_connection:connection});setDest(connection);onProject(p);}
 async function choose(){await run(async()=>{const d=await send('/api/github/publish',mode==='new'?{action:'create',name,private:privateRepo,projectId:project.id}:{action:'inspect',repository});await remember({repository:d.repository,branch:branch||d.branch,head:null});setNotice('Repository connected. Publish a new empty repository, or pull existing Studio changes before pushing.');});}
 const merged=incoming?mergeSources(incoming.base,incoming.local,incoming.remote,choices):null;
 return <div className="modal-backdrop"><section className="modal phase-two-modal" role="dialog" aria-modal="true" aria-label="GitHub sync"><h2>GitHub sync</h2><p>{project.name} · {connected?'Signed in as @'+login:'Connect GitHub in Settings.'}</p>{!connected?<Link className="primary-button" href="/settings">Connect GitHub</Link>:<>
 {dest?<div className="github-destination"><strong>{dest.repository}</strong><p>Branch: {dest.branch} · {dest.head?'Last synced '+dest.head.slice(0,8):'Not synced yet'}</p><button className="subtle-button" disabled={busy} onClick={()=>{setRepository(dest.repository);setBranch(dest.branch);setDest(null);setIncoming(null);setMode('existing');}}>Change repository or branch</button></div>:<form onSubmit={e=>{e.preventDefault();void choose()}}><label>Destination<select value={mode} onChange={e=>setMode(e.target.value as 'new'|'existing')}><option value="new">Create a new repository</option><option value="existing">Existing Studio repository</option></select></label>{mode==='new'?<><label>Repository name<input value={name} onChange={e=>setName(e.target.value)} required pattern="[a-zA-Z0-9_.-]+" maxLength={100}/></label><label>Visibility<select value={privateRepo?'private':'public'} onChange={e=>setPrivateRepo(e.target.value==='private')}><option value="private">Private</option><option value="public">Public — anyone can see source</option></select></label></>:<><label>Owner/repository<input required value={repository} onChange={e=>setRepository(e.target.value)}/></label><label>Branch (blank uses default)<input value={branch} onChange={e=>setBranch(e.target.value)} maxLength={200}/></label></>}<button className="primary-button" disabled={busy}>{mode==='new'?'Create repository':'Connect repository'}</button></form>}
 {dest&&<><p>Pull GitHub edits into a new Studio version, review conflicts, then publish. External files outside Studio’s managed source are preserved.</p><div className="settings-actions"><button className="subtle-button" disabled={busy} onClick={()=>run(async()=>{const d=await send('/api/github/sync',{connection:dest,projectId:project.id,files:revision.files,sql:revision.sql});setIncoming({...d,revisionId:revision.id,local:[...revision.files,{path:'schema.sql',content:revision.sql}]});setChoices({});setNotice('Review the incoming changes. Nothing has been saved yet.');})}>Pull & review GitHub changes</button><button className="primary-button" disabled={busy||!!incoming} onClick={()=>run(async()=>{const result=await send('/api/github/publish',{action:'push',expectedHead:dest.head,projectId:project.id,name:project.name,repository:dest.repository,branch:dest.branch,files:revision.files,sql:revision.sql,url:project.supabase_url,key:project.supabase_key});setCommit(result.url);await remember({...dest,head:result.sha});setNotice(result.unchanged?'GitHub already contains this version.':'Published. Vercel will deploy this commit if the repository is connected.');})}>Push saved version</button></div><p className="settings-help">Vercel preset: {isFullstack(revision.files)?'Next.js, default build settings.':'Other, no build command, repository root output.'} {isFullstack(revision.files)?'Edit app/, components/ and lib/ in GitHub.':'Edit source/ in GitHub; root index.html is the exported preview.'} Repository settings sync with this project; credentials remain private to your browser.</p><a href="https://vercel.com/new" target="_blank" rel="noreferrer">Import repository in Vercel ↗</a></>}
 {incoming&&merged&&dest&&<><h3>Incoming commit {incoming.head.slice(0,8)}</h3><p>{merged.changes.length} differing files · {merged.conflicts.length} unresolved conflicts. SQL is saved for review; it is never applied automatically.</p><SourceChanges changes={merged.changes} choices={choices} onChoice={(path,choice)=>setChoices(old=>({...old,[path]:choice}))}/><button className="primary-button" disabled={busy||!!merged.conflicts.length} onClick={()=>run(async()=>{if(revision.id!==incoming.revisionId)throw new Error('Studio changed during review. Pull again.');const latest=await send('/api/github/sync',{connection:dest,projectId:project.id,files:revision.files,sql:revision.sql});if(latest.head!==incoming.head)throw new Error('GitHub changed during review. Pull again.');const artifact=validateArtifact({name:project.name,summary:'Merged GitHub changes',files:merged.files.filter(f=>f.path!=='schema.sql'),sql:merged.files.find(f=>f.path==='schema.sql')?.content??''});if(isFullstack(artifact.files)!==isFullstack(revision.files))throw new Error('GitHub cannot switch this project’s runtime.');if(!sameSources(artifact.files,revision.files)||artifact.sql!==revision.sql){const r=await api(`/api/projects/${project.id}/edit`,'POST',{expectedRevision:incoming.revisionId,files:artifact.files,sql:artifact.sql,message:'Merge GitHub commit '+incoming.head});onSaved(r);}await remember({...dest,head:incoming.head});setIncoming(null);setNotice('Sync saved. You can push your merged version when ready.');})}>Save reviewed merge · 0 tokens</button><button className="subtle-button" disabled={busy} onClick={()=>setIncoming(null)}>Discard review</button></>}
 </>}{commit&&<p><a href={commit} target="_blank" rel="noreferrer">View commit ↗</a></p>}{error&&<p className="settings-error" role="alert">{error}</p>}{notice&&<p className="settings-notice" role="status">{notice}</p>}<button className="subtle-button" disabled={busy} onClick={onClose}>Close</button></section></div>;
}
