'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import type {Project,Revision} from '@/lib/types';
type Destination={repository:string;branch:string;url?:string};
export default function ProjectGithub({project,revision,onClose}:{project:Project;revision:Revision;onClose:()=>void}){
 const storageKey='5511-github:'+project.id;
 const [login,setLogin]=useState(''),[connected,setConnected]=useState(false),[dest,setDest]=useState<Destination|null>(null),[mode,setMode]=useState<'new'|'existing'>('new'),[name,setName]=useState(project.name.toLowerCase().replace(/[^a-z0-9-]/g,'-').slice(0,100)),[repository,setRepository]=useState(''),[privateRepo,setPrivateRepo]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[commit,setCommit]=useState('');
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(storageKey)??'null');if(saved?.repository&&saved?.branch){setDest(saved);setRepository(saved.repository)}}catch{}fetch('/api/github',{cache:'no-store'}).then(async r=>{const s=await r.json();if(!r.ok)throw new Error(s.error);setLogin(s.login);setConnected(s.connected)}).catch(e=>setError(e.message))},[storageKey]);
 async function send(body:unknown){const r=await fetch('/api/github/publish',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);return d}
 async function choose(){setBusy(true);setError('');try{const d=await send(mode==='new'?{action:'create',name,private:privateRepo,projectId:project.id}:{action:'inspect',repository});setDest(d);setRepository(d.repository);localStorage.setItem(storageKey,JSON.stringify(d));setNotice('Repository selected. Review the destination, then publish this version.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function publish(){if(!dest)return;setBusy(true);setError('');try{const result=await send({action:'push',projectId:project.id,name:project.name,repository:dest.repository,branch:dest.branch,files:revision.files,sql:revision.sql,url:project.supabase_url,key:project.supabase_key});setCommit(result.url);setNotice(result.unchanged?'GitHub already contains this version. No duplicate commit created.':'Saved version published to GitHub. Vercel will deploy it if this repository is connected.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="modal-backdrop"><section className="modal github-publish" role="dialog" aria-modal="true" aria-label="Publish to GitHub"><button className="modal-close icon-button" disabled={busy} onClick={onClose} aria-label="Close GitHub publishing">×</button><h2>Publish to GitHub</h2><p>{project.name} · {connected?'Signed in as @'+login:'Connect GitHub in Settings to publish.'}</p>{!connected?<Link className="primary-button" href="/settings">Connect GitHub</Link>:<>
 {dest?<div className="github-destination"><strong>{dest.repository}</strong><p>Branch: {dest.branch}</p><button className="subtle-button" disabled={busy} onClick={()=>{setDest(null);setMode('existing');setCommit('')}}>Change repository</button></div>:<form onSubmit={e=>{e.preventDefault();void choose()}}><label>Repository destination<select value={mode} onChange={e=>setMode(e.target.value as 'new'|'existing')} disabled={busy}><option value="new">Create a new repository in my account</option><option value="existing">Use an existing dedicated repository</option></select></label>{mode==='new'?<><label>Repository name<input value={name} onChange={e=>setName(e.target.value)} required pattern="[a-zA-Z0-9_.-]+" maxLength={100}/></label><label>Visibility<select value={privateRepo?'private':'public'} onChange={e=>setPrivateRepo(e.target.value==='private')}><option value="private">Private</option><option value="public">Public — anyone can see this source</option></select></label></>:<label>GitHub owner/repository<input value={repository} onChange={e=>setRepository(e.target.value)} placeholder="your-account/your-project" required/></label>}<button className="subtle-button" disabled={busy}>{busy?'Connecting…':mode==='new'?'Create repository':'Select repository'}</button></form>}
 {dest&&<><p>This publishes the current saved version: standalone app, original source, database schema, Vercel configuration, and README. Existing Studio files are updated in one commit. Other repository files are preserved.</p><button className="primary-button" disabled={busy} onClick={publish}>{busy?'Publishing…':'Publish saved version to GitHub'}</button><p className="settings-help">After the first publish, import this repository in Vercel with the Other framework preset, no build command, and the repository root as output. No Vercel token is needed here.</p><a href="https://vercel.com/new" target="_blank" rel="noreferrer">Import repository in Vercel ↗</a><p className="settings-help">Publishing is one way. GitHub changes are not imported into Studio. This destination is remembered in this browser; another device can select the same repository.</p></>}
 </>}{commit&&<p><a href={commit} target="_blank" rel="noreferrer">View commit on GitHub ↗</a></p>}{error&&<p className="settings-error" role="alert">{error}</p>}{notice&&<p className="settings-notice" role="status">{notice}</p>}</section></div>
}
