'use client';
import {useEffect,useState} from 'react';
import {newSection,sectionKinds,sectionStarters,sectionSchema,sectionDocument,type Section} from '@/lib/section-studio';
const draftKey='5511-section-studio-draft-v1';
export default function SectionStudio({initial,onSave,onClose}:{initial?:Section;onSave:(s:Section)=>Promise<void>;onClose:()=>void}){
 const [draft,setDraft]=useState<Section>(()=>initial??newSection('hero',crypto.randomUUID())),[loaded,setLoaded]=useState(false),[mobile,setMobile]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{if(!initial)try{const saved=localStorage.getItem(draftKey);if(saved)setDraft(sectionSchema.parse(JSON.parse(saved)));}catch{}setLoaded(true)},[initial]);
 useEffect(()=>{if(loaded)try{localStorage.setItem(draftKey,JSON.stringify(draft));}catch{}},[draft,loaded]);
 const result=sectionSchema.safeParse(draft),preview=result.success?sectionDocument(result.data,true):'';
 function update(p:Partial<Section>){setDraft(s=>({...s,...p}));setMessage('')}
 return <section className="section-studio" aria-label="Section Studio"><header className="section-studio-heading"><div><small>YOUR REUSABLE DESIGN WORKSHOP</small><h2>Section Studio</h2><p>Design once. Reuse across projects. No AI tokens needed.</p></div><button className="subtle-button" onClick={onClose} disabled={busy}>Back to library</button></header><div className="section-workspace"><aside>
 <label>Starting layout<select value={draft.kind} onChange={e=>{const next=newSection(e.target.value as Section['kind'],draft.id);update({...next,name:draft.name===sectionStarters[draft.kind].name?next.name:draft.name,accent:draft.accent,dark:draft.dark,rounded:draft.rounded});}}>{sectionKinds.map(k=><option key={k} value={k}>{sectionStarters[k].name}</option>)}</select></label>
 <label>Library name<input maxLength={80} value={draft.name} onChange={e=>update({name:e.target.value})}/></label>
 <label>Eyebrow<input maxLength={100} value={draft.eyebrow} onChange={e=>update({eyebrow:e.target.value})}/></label>
 <label>Heading<input maxLength={160} value={draft.title} onChange={e=>update({title:e.target.value})}/></label>
 <label>Description<textarea maxLength={700} value={draft.body} onChange={e=>update({body:e.target.value})}/></label>
 <label>Button label · leave blank to hide<input maxLength={60} value={draft.button} onChange={e=>update({button:e.target.value})}/></label>
 <label>Button destination<input maxLength={500} value={draft.href} onChange={e=>update({href:e.target.value})}/></label>
 <div className="section-style-controls"><label>Accent<input type="color" value={draft.accent} onChange={e=>update({accent:e.target.value})}/></label><label><input type="checkbox" checked={draft.dark} onChange={e=>update({dark:e.target.checked})}/> Dark</label><label><input type="checkbox" checked={draft.rounded} onChange={e=>update({rounded:e.target.checked})}/> Rounded</label></div>
 {!['hero','cta'].includes(draft.kind)&&<fieldset><legend>Section items</legend>{draft.items.map((item,i)=><div className="section-item-editor" key={i}><label>Item {i+1} title<input maxLength={100} value={item.title} onChange={e=>update({items:draft.items.map((x,n)=>n===i?{...x,title:e.target.value}:x)})}/></label><label>Item {i+1} description<textarea maxLength={500} value={item.body} onChange={e=>update({items:draft.items.map((x,n)=>n===i?{...x,body:e.target.value}:x)})}/></label><button className="subtle-button" disabled={draft.items.length===1} onClick={()=>update({items:draft.items.filter((_,n)=>n!==i)})}>Remove item {i+1}</button></div>)}<button className="subtle-button" disabled={draft.items.length>=6} onClick={()=>update({items:[...draft.items,{title:'New item',body:'Add your details.'}]})}>Add item</button></fieldset>}
 </aside><div className="section-preview-area"><div className="section-preview-toolbar"><strong>Live preview</strong><button className="subtle-button" aria-pressed={mobile} onClick={()=>setMobile(x=>!x)}>{mobile?'Show desktop':'Show mobile'}</button></div>{result.success?<iframe title="Section design preview" sandbox="" srcDoc={preview} style={{width:mobile?'375px':'100%',maxWidth:'100%'}}/>:<p role="alert">{result.error.issues[0]?.message}</p>}<p>Preview links are disabled. Buttons link to the destination you set after installation.</p></div></div>
 <footer className="section-studio-footer"><div><p role="status">{message||'Your draft is kept in this browser. Save to make it available in your library.'}</p></div><button className="primary-button" disabled={busy||!result.success} onClick={async()=>{setBusy(true);setMessage('');try{await onSave(sectionSchema.parse(draft));setMessage('Saved to your library. Keep designing or return to insert your section.');setDraft(s=>({...s,id:crypto.randomUUID()}));}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}}>{busy?'Saving…':'Save a copy to library'}</button></footer></section>;
}
