'use client';
import {useEffect,useState} from 'react';
import type {Project,Revision} from '@/lib/types';
type Send=(path:string,method?:string,body?:unknown)=>Promise<any>;
export default function TeamAccess({project,revisions,api,onClose,onRestored}:{project:Project;revisions:Revision[];api:Send;onClose:()=>void;onRestored:(revision:Revision)=>void}){
 const owner=project.access_role==='owner';const [members,setMembers]=useState<{id:string;email:string;role:string}[]>([]),[email,setEmail]=useState(''),[role,setRole]=useState('editor'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[active,setActive]=useState(false),[storage,setStorage]=useState({configured:false,saved:false}),[version,setVersion]=useState(project.current_revision_id??'');
 async function refresh(){const result=await api(`/api/projects/${project.id}/storage`);setStorage(result);if(owner){setMembers(await api(`/api/projects/${project.id}/team`));setActive(true)}}
 useEffect(()=>{refresh().catch(e=>setError(e.message))},[project.id]);
 async function run(action:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await action()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="modal-backdrop"><section className="modal github-publish" role="dialog" aria-modal="true" aria-label="Team and storage"><button className="modal-close icon-button" disabled={busy} onClick={onClose} aria-label="Close team settings">×</button><h2>Team &amp; storage</h2><p>{project.name} · Your access: {project.access_role??'owner'}</p>
 {owner?<><h3>Employee access</h3><p>Grant access by email, then share your hosted Studio address. Employees sign in or register with that email and verify it. No invitation email is sent here.</p><form onSubmit={e=>{e.preventDefault();void run(async()=>{await api(`/api/projects/${project.id}/team`,'POST',{email,role});setEmail('');await refresh();setNotice('Access saved. The verified employee account can open this project.')})}}><label>Employee email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required maxLength={254}/></label><label>Role<select value={role} onChange={e=>setRole(e.target.value)}><option value="editor">Editor — build and edit</option><option value="viewer">Viewer — read only</option></select></label><button className="primary-button" disabled={busy||!active}>Grant project access</button></form>{members.map(m=><div className="team-member" key={m.id}><div><b>{m.email}</b><small>{m.role}</small></div><button className="subtle-button" disabled={busy} onClick={()=>void run(async()=>{await api(`/api/projects/${project.id}/team`,'DELETE',{id:m.id});await refresh();setNotice('Project access removed.')})}>Remove access</button></div>)}</>:<p>Ask the project owner to add or remove employees. Your access applies only to this project.</p>}
 <h3>Supabase Storage</h3><p>{!storage.configured?'Server storage is not configured yet. Saved versions remain in the cloud workspace.':storage.saved?'The current version is backed up in Supabase Storage.':'The current version has not been backed up to Supabase Storage yet.'}</p>{project.access_role!=='viewer'&&<><button className="subtle-button" disabled={busy||!storage.configured} onClick={()=>void run(async()=>{const result=await api(`/api/projects/${project.id}/storage`,'POST',{action:'backup'});setNotice(result.message);await refresh()})}>Back up saved versions</button>{!!revisions.length&&<><label>Restore a stored version<select value={version} onChange={e=>setVersion(e.target.value)}>{revisions.map((r,i)=><option value={r.id} key={r.id}>Version {revisions.length-i} · {new Date(r.created_at).toLocaleString()}</option>)}</select></label><button className="subtle-button" disabled={busy||!storage.configured||!version} onClick={()=>void run(async()=>{const rev=await api(`/api/projects/${project.id}/storage`,'POST',{action:'restore',revisionId:version,expectedRevision:project.current_revision_id});onRestored(rev);setNotice('Stored version restored as a new saved version.');await refresh()})}>Restore as new version</button></>}</>}
 <p className="settings-help">Drafts belong to each employee. Saved app versions are shared. Concurrent saves are checked; reopen if someone saves a newer version first.</p>{error&&<p className="settings-error" role="alert">{error}</p>}{notice&&<p className="settings-notice" role="status">{notice}</p>}</section></div>
}
