'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {ArrowLeft,RefreshCw} from 'lucide-react';
import {legacyTokenTotal} from '@/lib/browser-workspace';
import {defaultLimits,type UsageSummary} from '@/lib/usage-types';
export default function UsagePage(){
 const [data,setData]=useState<UsageSummary|null>(null),[limits,setLimits]=useState(defaultLimits),[legacy,setLegacy]=useState(0),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 async function refresh(){try{setError('');const r=await fetch('/api/usage',{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);setLimits(d.limits)}catch(e){setError((e as Error).message)}}
 useEffect(()=>{refresh();legacyTokenTotal().then(setLegacy).catch(()=>{})},[]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setNotice('');try{const r=await fetch('/api/usage',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(limits)});const result=await r.json();if(!r.ok)throw new Error(result.error);await refresh();setNotice('Token limits saved.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <main className="settings-page"><Link className="subtle-button" href="/"><ArrowLeft size={15}/>Back to Studio</Link><header><p className="eyebrow">5511 STUDIO</p><h1>Token usage</h1><p>See what each build used. Set limits before the next request.</p></header>{error&&<p role="alert" className="settings-error">{error} <Link href="/settings">Open Settings</Link></p>}
 {data&&<><div className="usage-counters">{[['Last 24 hours',data.today.total],['Cached input¹',data.today.cachedInput],['Output²',data.today.output],['Tracked all time',data.allTime.total]].map(([label,value])=><div key={label}><span>{label}</span><strong>{Number(value).toLocaleString()}</strong></div>)}</div><p className="usage-explainer">¹ Cached input is included in input tokens, not added again. ² Reasoning tokens are included in output. These are token counts, not a dollar invoice. Tracking starts when this feature is enabled.</p>{legacy>0&&<p className="usage-explainer">Older saved projects: {legacy.toLocaleString()} tokens recorded before detailed tracking. Their input/output split is unavailable.</p>}{data.reserved>0&&<p className="settings-notice">{data.reserved.toLocaleString()} tokens reserved for running or unconfirmed attempts. Unknown provider usage is never shown as zero.</p>}
 <section className="settings-card"><h2>Usage limits</h2><p>Applies to this API key on this Studio server, across projects and tabs. These limits do not cover other apps using your key.</p><form onSubmit={save}><div className="usage-limit-grid">{([{key:'dailyTokens',label:'Token budget · rolling 24 hours',min:1000,max:2000000},{key:'maxOutputTokens',label:'Maximum output per build',min:1000,max:18000},{key:'maxInputCharacters',label:'Maximum input characters',min:1000,max:150000},{key:'dailyBuilds',label:'Builds · rolling 24 hours',min:1,max:100}] as const).map(f=><label key={f.key}>{f.label}<input type="number" required min={f.min} max={f.max} value={limits[f.key]} onChange={e=>setLimits(l=>({...l,[f.key]:Number(e.target.value)}))}/></label>)}</div><div className="settings-actions"><button disabled={busy} className="primary-button">Save limits</button></div></form><p className="settings-help">Before a build, Studio reserves a conservative allowance for its input plus the output cap. Afterward, reported usage replaces that reservation. If a request times out, the reservation stays until it ages out of the 24-hour window. Output caps can leave a large build unfinished; previous versions stay safe.</p></section>
 <section className="settings-card"><div className="settings-card-title"><div><h2>Build history</h2><p>All tracked attempts, including failures</p></div><button onClick={refresh} className="subtle-button"><RefreshCw size={14}/>Refresh</button></div><div className="usage-table-wrap"><table className="usage-table"><thead><tr><th>Project / model</th><th>Status</th><th>Input</th><th>Cached¹</th><th>Output²</th><th>Total</th></tr></thead><tbody>{data.entries.map(e=><tr key={e.id}><td>{e.name}<small>{e.model} · {new Date(e.createdAt).toLocaleString()}</small>{e.reused>0&&<small>Reused {e.reused} time(s) · no extra generation</small>}</td><td>{e.status}{e.error&&<small>{e.error}</small>}</td><td>{e.usage?.input.toLocaleString()??'Unknown'}</td><td>{e.usage?.cachedInput.toLocaleString()??'—'}</td><td>{e.usage?.output.toLocaleString()??'—'}</td><td>{e.usage?.total.toLocaleString()??'Reserved '+e.reservation.toLocaleString()}</td></tr>)}</tbody></table>{!data.entries.length&&<p className="usage-explainer">No tracked builds yet. Existing saved versions remain available.</p>}</div></section></>}{notice&&<p role="status" className="settings-notice">{notice}</p>}
 </main>
}
