import {authorize,ownedProject,failure,readBody,HttpError} from '@/lib/server';
import {requireEditor} from '@/lib/project-access';
import {requireSameOrigin,credential} from '@/lib/credentials';
import {generateProjectImage,imageGenerationSchema,IMAGE_MODEL} from '@/lib/image-generation';
import {z} from 'zod';
export const maxDuration=240;
type Context={params:Promise<{id:string}>};
const columns='id,label,prompt,status,data_url,error,created_at,model,cost_usd';
export async function GET(request:Request,ctx:Context){try{const {db}=await authorize(request);const {id}=await ctx.params;await ownedProject(db,id);const imageId=new URL(request.url).searchParams.get('download');if(imageId){z.uuid().parse(imageId);const {data,error}=await db.from('studio_project_images').select('original_data_url').eq('project_id',id).eq('id',imageId).single();if(error||!data?.original_data_url)throw new HttpError(404,'Original image unavailable.');return Response.json(data,{headers:{'Cache-Control':'no-store'}});}const offset=z.coerce.number().int().min(0).max(100000).parse(new URL(request.url).searchParams.get('offset')??0);const {data,error}=await db.from('studio_project_images').select(columns).eq('project_id',id).order('created_at',{ascending:false}).order('id').range(offset,offset+7);if(error)throw new HttpError(503,'Image library storage is not configured.');return Response.json({images:data,nextOffset:data?.length===8?offset+8:null},{headers:{'Cache-Control':'no-store'}})}catch(e){return failure(e)}}
export async function POST(request:Request,ctx:Context){try{requireSameOrigin(request);const {db,user}=await authorize(request);const {id}=await ctx.params;await ownedProject(db,id);await requireEditor(db,id,user.id);const input=imageGenerationSchema.parse(await readBody(request,10000));const key=credential(request,'openai')||process.env.OPENAI_API_KEY;if(!key)throw new HttpError(400,'Connect OpenAI in Settings first.');
 const {data:existing}=await db.from('studio_project_images').select(columns).eq('project_id',id).eq('id',input.requestId).maybeSingle();if(existing)return Response.json(existing);
 const {error:insertError}=await db.from('studio_project_images').insert({id:input.requestId,project_id:id,created_by:user.id,label:input.label,prompt:input.prompt,model:IMAGE_MODEL,status:'generating'});if(insertError)throw new HttpError(409,'Choose a unique image label, or reopen the library to check your previous request.');
 try{const result=await generateProjectImage(key,id,input);const {data,error}=await db.from('studio_project_images').update({...result,status:'ready'}).eq('project_id',id).eq('id',input.requestId).select(columns).single();if(error)throw new Error('Could not save generated image.');return Response.json(data,{headers:{'Cache-Control':'no-store'}});}catch(e){const message=e instanceof HttpError?e.message:'Image generation did not finish. Check Usage before trying again. Your OpenAI account must have access to GPT Image 2.5 Sunburst.';await db.from('studio_project_images').update({status:'failed',error:message}).eq('project_id',id).eq('id',input.requestId);throw new HttpError(502,message);}
 }catch(e){return failure(e)}}
export async function PATCH(request:Request,ctx:Context){try{requireSameOrigin(request);const {db,user}=await authorize(request);const {id}=await ctx.params;await requireEditor(db,id,user.id);const input=z.object({imageId:z.uuid(),label:z.string().trim().min(1).max(100)}).parse(await readBody(request,1000));const {data,error}=await db.from('studio_project_images').update({label:input.label}).eq('project_id',id).eq('id',input.imageId).select(columns).single();if(error)throw new HttpError(409,'Choose a unique image label.');return Response.json(data)}catch(e){return failure(e)}}
